/**
 * Default services — single unified list.
 * Every service is dynamic with form editor capabilities.
 * Restructured: 6 logical groups, no duplicates, sequential sort_order 1–34.
 *
 * AUDIT LOG (v2):
 * - Removed orphan `professional-community` and `parents-interaction` (replaced by perf- versions)
 * - Removed duplicate `job-duties-forms` from tools (accessed via perf-job-duties in performance)
 * - Removed duplicate `improve-results` from planning (accessed via perf-improve-results in performance)
 * - Fixed sort_order: sequential 1–34, no duplicates or gaps
 * - Total services: 30 unique entries across 6 groups
 */
import type { ServiceDefinition } from '@/types';

export const DEFAULT_SERVICES: ServiceDefinition[] = [
    // ══════════════════════════════════════════════
    // ── 1. التحليل والاختبارات ──
    // ══════════════════════════════════════════════
    {
        id: 'analyses', slug: 'analyses', category: 'analysis',
        name_ar: 'تحليل النتائج', name_en: 'Results Analysis',
        description_ar: 'تحليل نتائج الاختبارات واستخراج التقارير والإحصائيات التفصيلية مع رسوم بيانية تفاعلية',
        description_en: 'Analyze test results with advanced tools, detailed reports, statistics, and interactive charts',
        icon: 'BarChart3', color: 'bg-blue-500', gradient: 'from-blue-500 to-indigo-600',
        route: '/analyze-results', service_type: 'interactive',
        admin_href: '/admin/educational-services/tests',
        features: [], is_active: true, sort_order: 1,
        requires_auth: false, requires_subscription: false,
        is_new: false, is_popular: true, is_premium: false,
    },
    {
        id: 'tests', slug: 'tests', category: 'analysis',
        name_ar: 'الاختبارات', name_en: 'Tests',
        description_ar: 'إنشاء وإدارة الاختبارات وتسجيل درجات الطلاب مع بنك أسئلة شامل',
        description_en: 'Create and manage tests with student grading and question bank',
        icon: 'FileQuestion', color: 'bg-cyan-500', gradient: 'from-cyan-500 to-teal-500',
        route: '/tests', service_type: 'interactive',
        admin_href: '/admin/educational-services/tests',
        features: [], is_active: true, sort_order: 2,
        requires_auth: true, requires_subscription: false,
        is_new: false, is_popular: false, is_premium: false,
    },
    {
        id: 'question-bank', slug: 'question-bank', category: 'analysis',
        name_ar: 'بنك الأسئلة', name_en: 'Question Bank',
        description_ar: 'إدارة بنك أسئلة شامل مصنّف حسب المادة والمستوى وتصنيف بلوم',
        description_en: 'Manage a comprehensive question bank by subject, level, and Bloom\'s taxonomy',
        icon: 'Brain', color: 'bg-rose-500', gradient: 'from-rose-500 to-pink-600',
        route: '/question-bank', service_type: 'interactive',
        admin_href: '/admin/educational-services/question-bank',
        features: [], is_active: true, sort_order: 3,
        requires_auth: true, requires_subscription: false,
        is_new: true, is_popular: false, is_premium: false,
    },
    {
        id: 'results-analysis-tools', slug: 'results-analysis-tools', category: 'analysis',
        name_ar: 'أدوات تحليل النتائج', name_en: 'Results Analysis Tools',
        description_ar: 'أدوات تحليل نتائج الاختبارات لجميع المراحل مع إحصائيات تلقائية وتوزيع الدرجات',
        description_en: 'Test results analysis tools for all stages with automatic statistics and grade distribution',
        icon: 'TrendingUp', color: 'bg-cyan-600', gradient: 'from-cyan-600 to-teal-700',
        route: '/results-analysis-tools', service_type: 'interactive',
        admin_href: '/admin/educational-services/static-tools/results-analysis-tools',
        features: [], is_active: true, sort_order: 4,
        requires_auth: false, requires_subscription: false,
        is_new: false, is_popular: true, is_premium: false,
    },


    // ══════════════════════════════════════════════
    // ── 2. الشهادات المتنوعة ──
    // ══════════════════════════════════════════════
    {
        id: 'certificates', slug: 'certificates', category: 'certificates',
        name_ar: 'شهادات شكر وتقدير', name_en: 'Appreciation Certificates',
        description_ar: 'إنشاء شهادات شكر وتقدير بتصاميم متعددة وجاهزة مع إنشاء جماعي',
        description_en: 'Create appreciation certificates with multiple professional designs and bulk generation',
        icon: 'Award', color: 'bg-amber-500', gradient: 'from-amber-500 to-orange-500',
        route: '/certificates', service_type: 'interactive',
        admin_href: '/admin/educational-services/certificates',
        features: [], is_active: true, sort_order: 5,
        requires_auth: true, requires_subscription: false,
        is_new: false, is_popular: true, is_premium: false,
    },
    {
        id: 'other-certificates', slug: 'other-certificates', category: 'certificates',
        name_ar: 'شهادات متنوعة', name_en: 'Various Certificates',
        description_ar: 'شهادات تخرج ونجاح وحضور دورات وشهادات متنوعة بتصاميم احترافية',
        description_en: 'Graduation, success, course attendance, and various certificates with professional designs',
        icon: 'GraduationCap', color: 'bg-orange-500', gradient: 'from-orange-500 to-amber-600',
        route: '/other-certificates', service_type: 'interactive',
        admin_href: '/admin/educational-services/static-tools/other-certificates',
        features: [], is_active: true, sort_order: 6,
        requires_auth: false, requires_subscription: false,
        is_new: false, is_popular: false, is_premium: false,
    },
    // [AUDIT] appreciation-certificates removed — functionally identical to certificates

    // ══════════════════════════════════════════════
    // ── 3. تقييم الأداء الوظيفي — كل بند مباشرة ──
    // ══════════════════════════════════════════════
    {
        id: 'perf-job-duties', slug: 'perf-job-duties', category: 'performance',
        name_ar: '١. أداء الواجبات الوظيفية', name_en: '1. Job Duties Performance',
        description_ar: 'الإذاعة المدرسية والأنشطة اللاصفية وحصص الانتظار وتوثيق المهام',
        description_en: 'School broadcast, extracurricular activities, substitute lessons',
        icon: 'Briefcase', color: 'bg-blue-600', gradient: 'from-blue-600 to-blue-700',
        route: '/performance-evidence-forms?section=job-duties', service_type: 'interactive',
        admin_href: '/admin/educational-services/static-tools/performance-evidence-forms',
        features: [], is_active: true, sort_order: 7,
        requires_auth: false, requires_subscription: false,
        is_new: false, is_popular: false, is_premium: false,
    },
    {
        id: 'perf-professional-community', slug: 'perf-professional-community', category: 'performance',
        name_ar: '٢. التفاعل مع المجتمع المهني', name_en: '2. Professional Community',
        description_ar: 'مجتمعات التعلم المهنية وتبادل الزيارات والاجتماعات المهنية',
        description_en: 'Professional learning communities, peer visits & meetings',
        icon: 'Users', color: 'bg-indigo-600', gradient: 'from-indigo-600 to-blue-700',
        route: '/performance-evidence-forms?section=professional-community', service_type: 'interactive',
        admin_href: '/admin/educational-services/static-tools/performance-evidence-forms',
        features: [], is_active: true, sort_order: 8,
        requires_auth: false, requires_subscription: false,
        is_new: false, is_popular: false, is_premium: false,
    },
    {
        id: 'perf-parents-interaction', slug: 'perf-parents-interaction', category: 'performance',
        name_ar: '٣. التفاعل مع أولياء الأمور', name_en: '3. Parents Interaction',
        description_ar: 'تقارير الاجتماعات والرسائل والمتابعة مع أولياء الأمور',
        description_en: 'Parent meetings, messages, and follow-up reports',
        icon: 'Users', color: 'bg-teal-600', gradient: 'from-teal-600 to-emerald-600',
        route: '/performance-evidence-forms?section=parents-interaction', service_type: 'interactive',
        admin_href: '/admin/educational-services/static-tools/performance-evidence-forms',
        features: [], is_active: true, sort_order: 9,
        requires_auth: false, requires_subscription: false,
        is_new: false, is_popular: false, is_premium: false,
    },
    {
        id: 'perf-strategies', slug: 'perf-strategies', category: 'performance',
        name_ar: '٤. استراتيجيات التدريس', name_en: '4. Teaching Strategies',
        description_ar: 'فكر زاوج شارك، التعلم التعاوني، الفصل المقلوب وغيرها',
        description_en: 'Think-Pair-Share, cooperative learning, flipped classroom & more',
        icon: 'Brain', color: 'bg-amber-600', gradient: 'from-amber-600 to-orange-600',
        route: '/performance-evidence-forms?section=strategies', service_type: 'interactive',
        admin_href: '/admin/educational-services/static-tools/performance-evidence-forms',
        features: [], is_active: true, sort_order: 10,
        requires_auth: false, requires_subscription: false,
        is_new: false, is_popular: true, is_premium: false,
    },
    {
        id: 'perf-improve-results', slug: 'perf-improve-results', category: 'performance',
        name_ar: '٥. تحسين نتائج المتعلمين', name_en: '5. Improving Learner Results',
        description_ar: 'أدوات وخطط لتحسين نتائج الطلاب وقياس أثر التدخلات',
        description_en: 'Tools and plans for improving student results',
        icon: 'TrendingUp', color: 'bg-green-600', gradient: 'from-green-600 to-emerald-700',
        route: '/improve-results', service_type: 'interactive',
        admin_href: '/admin/educational-services/static-tools/performance-evidence-forms',
        features: [], is_active: true, sort_order: 11,
        requires_auth: false, requires_subscription: false,
        is_new: false, is_popular: false, is_premium: false,
    },
    {
        id: 'perf-learning-plan', slug: 'perf-learning-plan', category: 'performance',
        name_ar: '٦. إعداد وتنفيذ خطة التعلم', name_en: '6. Learning Plans',
        description_ar: 'الخطط التعليمية العلاجية والإثرائية وتوزيع المنهج',
        description_en: 'Educational, remedial, and enrichment plans',
        icon: 'FileText', color: 'bg-emerald-600', gradient: 'from-emerald-600 to-green-700',
        route: '/plans', service_type: 'interactive',
        admin_href: '/admin/educational-services/static-tools/performance-evidence-forms',
        features: [], is_active: true, sort_order: 12,
        requires_auth: false, requires_subscription: false,
        is_new: false, is_popular: false, is_premium: false,
    },
    {
        id: 'perf-technical', slug: 'perf-technical', category: 'performance',
        name_ar: '٧. توظيف التقنيات التعليمية', name_en: '7. Learning Technologies',
        description_ar: 'تقارير استخدام البرامج والأدوات التقنية في التدريس',
        description_en: 'Reports on using technology programs and tools in teaching',
        icon: 'Wrench', color: 'bg-cyan-600', gradient: 'from-cyan-600 to-teal-700',
        route: '/performance-evidence-forms?section=technical', service_type: 'interactive',
        admin_href: '/admin/educational-services/static-tools/performance-evidence-forms',
        features: [], is_active: true, sort_order: 13,
        requires_auth: false, requires_subscription: false,
        is_new: false, is_popular: true, is_premium: false,
    },
    {
        id: 'perf-school-environment', slug: 'perf-school-environment', category: 'performance',
        name_ar: '٨. تهيئة البيئة التعليمية', name_en: '8. Educational Environment',
        description_ar: 'نماذج تقييم وتوثيق البيئة المدرسية الجاذبة',
        description_en: 'School environment assessment and documentation',
        icon: 'BookOpen', color: 'bg-lime-600', gradient: 'from-lime-600 to-green-700',
        route: '/performance-evidence-forms?section=school-environment', service_type: 'interactive',
        admin_href: '/admin/educational-services/static-tools/performance-evidence-forms',
        features: [], is_active: true, sort_order: 14,
        requires_auth: false, requires_subscription: false,
        is_new: false, is_popular: false, is_premium: false,
    },
    {
        id: 'perf-classroom-management', slug: 'perf-classroom-management', category: 'performance',
        name_ar: '٩. الإدارة الصفية', name_en: '9. Classroom Management',
        description_ar: 'التعزيز الإيجابي، التنظيم المادي، القواعد الصفية',
        description_en: 'Positive reinforcement, physical organization, class rules',
        icon: 'Shield', color: 'bg-rose-600', gradient: 'from-rose-600 to-pink-600',
        route: '/performance-evidence-forms?section=classroom-management', service_type: 'interactive',
        admin_href: '/admin/educational-services/static-tools/performance-evidence-forms',
        features: [], is_active: true, sort_order: 15,
        requires_auth: false, requires_subscription: false,
        is_new: false, is_popular: false, is_premium: false,
    },
    {
        id: 'perf-results-analysis', slug: 'perf-results-analysis', category: 'performance',
        name_ar: '١٠. تحليل نتائج المتعلمين', name_en: '10. Results Analysis',
        description_ar: 'تقارير تحليل وتشخيص نتائج الطلاب لجميع المراحل',
        description_en: 'Student results analysis for all academic stages',
        icon: 'PieChart', color: 'bg-blue-700', gradient: 'from-blue-700 to-indigo-800',
        route: '/analyze-results', service_type: 'interactive',
        admin_href: '/admin/educational-services/static-tools/performance-evidence-forms',
        features: [], is_active: true, sort_order: 16,
        requires_auth: false, requires_subscription: false,
        is_new: false, is_popular: true, is_premium: false,
    },
    {
        id: 'perf-assessment-methods', slug: 'perf-assessment-methods', category: 'performance',
        name_ar: '١١. تنوع أساليب التقويم', name_en: '11. Assessment Methods',
        description_ar: 'التقويم التكويني، الختامي، الذاتي، الأقران، الأداء',
        description_en: 'Formative, summative, self, peer, performance assessment',
        icon: 'CheckCircle', color: 'bg-purple-600', gradient: 'from-purple-600 to-violet-700',
        route: '/performance-evidence-forms?section=assessment-methods', service_type: 'interactive',
        admin_href: '/admin/educational-services/static-tools/performance-evidence-forms',
        features: [], is_active: true, sort_order: 17,
        requires_auth: false, requires_subscription: false,
        is_new: false, is_popular: false, is_premium: false,
    },


    // ══════════════════════════════════════════════
    // ── 4. السجلات والملفات المدرسية ──
    // ══════════════════════════════════════════════
    {
        id: 'achievements', slug: 'achievements', category: 'records',
        name_ar: 'التوثيق والإنجازات', name_en: 'Documentation & Achievements',
        description_ar: 'توثيق الإنجازات اليومية والأسبوعية والشهرية مع نماذج وتقارير توثيق احترافية جاهزة للتعبئة والطباعة',
        description_en: 'Document daily, weekly, and monthly achievements with professional documentation forms ready to fill and print',
        icon: 'Trophy', color: 'bg-purple-500', gradient: 'from-purple-500 to-violet-500',
        route: '/achievements', service_type: 'interactive',
        admin_href: '/admin/educational-services/achievements',
        features: [], is_active: true, sort_order: 18,
        requires_auth: true, requires_subscription: false,
        is_new: false, is_popular: true, is_premium: false,
    },
    {
        id: 'knowledge-production', slug: 'knowledge-production', category: 'records',
        name_ar: 'الإنتاج المعرفي', name_en: 'Knowledge Production',
        description_ar: 'توثيق الإنتاج المعرفي من أبحاث ومقالات وأوراق عمل ومبادرات',
        description_en: 'Document knowledge production including research, articles, and initiatives',
        icon: 'Lightbulb', color: 'bg-yellow-500', gradient: 'from-yellow-500 to-amber-500',
        route: '/knowledge-production', service_type: 'interactive',
        admin_href: '/admin/educational-services/knowledge-production',
        features: [], is_active: true, sort_order: 19,
        requires_auth: true, requires_subscription: false,
        is_new: true, is_popular: false, is_premium: false,
    },
    {
        id: 'follow-up-log', slug: 'follow-up-log', category: 'records',
        name_ar: 'سجل المتابعة', name_en: 'Follow-up Log',
        description_ar: 'سجل متابعة شامل لتوثيق الزيارات والتوصيات',
        description_en: 'Comprehensive follow-up log for visits and recommendations',
        icon: 'ScrollText', color: 'bg-emerald-500', gradient: 'from-emerald-500 to-green-500',
        route: '/follow-up-log', service_type: 'interactive',
        admin_href: '/admin/educational-services/follow-up-log',
        features: [], is_active: true, sort_order: 20,
        requires_auth: true, requires_subscription: false,
        is_new: true, is_popular: false, is_premium: false,
    },
    {
        id: 'portfolio', slug: 'portfolio', category: 'records',
        name_ar: 'ملف الإنجاز', name_en: 'Portfolio',
        description_ar: 'ملف إنجاز رقمي شامل لجمع الشهادات والإنجازات والتدريبات',
        description_en: 'Comprehensive digital portfolio for certificates and achievements',
        icon: 'FolderArchive', color: 'bg-rose-500', gradient: 'from-rose-500 to-pink-500',
        route: '/portfolio', service_type: 'interactive',
        admin_href: '/admin/educational-services/static-tools/portfolio',
        features: [], is_active: true, sort_order: 21,
        requires_auth: true, requires_subscription: false,
        is_new: true, is_popular: true, is_premium: false,
    },

    {
        id: 'documentation-forms', slug: 'documentation-forms', category: 'records',
        name_ar: 'نماذج وتقارير التوثيق', name_en: 'Documentation Forms & Reports',
        description_ar: 'نماذج توثيق احترافية للمعلمين: برامج، استراتيجيات، تقارير وشواهد جاهزة للتعبئة والطباعة',
        description_en: 'Professional documentation forms for teachers: programs, strategies, reports ready for filling and printing',
        icon: 'ScrollText', color: 'bg-teal-600', gradient: 'from-teal-500 to-emerald-600',
        route: '/documentation-forms', service_type: 'interactive',
        admin_href: '/admin/educational-services/static-tools/documentation-forms',
        features: [], is_active: true, sort_order: 22,
        requires_auth: false, requires_subscription: false,
        is_new: false, is_popular: true, is_premium: false,
    },
    {
        id: 'achievement-report-builder', slug: 'achievement-report-builder', category: 'records',
        name_ar: 'منشئ تقارير الإنجاز', name_en: 'Achievement Report Builder',
        description_ar: 'إنشاء تقارير إنجاز احترافية جاهزة للطباعة والمشاركة',
        description_en: 'Create professional achievement reports ready for printing and sharing',
        icon: 'FileSpreadsheet', color: 'bg-indigo-500', gradient: 'from-indigo-500 to-purple-600',
        route: '/achievement-report-builder', service_type: 'interactive',
        admin_href: '/admin/educational-services/static-tools/achievement-report-builder',
        features: [], is_active: true, sort_order: 23,
        requires_auth: false, requires_subscription: false,
        is_new: true, is_popular: false, is_premium: false,
    },

    // ══════════════════════════════════════════════
    // ── 5. التخطيط والتوزيعات ──
    // ══════════════════════════════════════════════
    {
        id: 'plans', slug: 'plans', category: 'planning',
        name_ar: 'الخطط التعليمية', name_en: 'Educational Plans',
        description_ar: 'إنشاء الخطط العلاجية والإثرائية وتوزيع المنهج',
        description_en: 'Create remedial and enrichment plans with curriculum distribution',
        icon: 'ClipboardList', color: 'bg-green-500', gradient: 'from-green-500 to-emerald-500',
        route: '/plans', service_type: 'interactive',
        admin_href: '/admin/educational-services/plans',
        features: [], is_active: true, sort_order: 24,
        requires_auth: true, requires_subscription: false,
        is_new: false, is_popular: true, is_premium: false,
    },
    {
        id: 'distributions', slug: 'distributions', category: 'planning',
        name_ar: 'التوزيعات', name_en: 'Distributions',
        description_ar: 'إعداد توزيعات المنهج الأسبوعية والشهرية والفصلية',
        description_en: 'Prepare weekly, monthly, and semester curriculum distributions',
        icon: 'CalendarDays', color: 'bg-teal-500', gradient: 'from-teal-500 to-cyan-500',
        route: '/distributions', service_type: 'interactive',
        admin_href: '/admin/educational-services/distributions',
        features: [], is_active: true, sort_order: 25,
        requires_auth: true, requires_subscription: false,
        is_new: true, is_popular: false, is_premium: false,
    },
    {
        id: 'weekly-plan-builder', slug: 'weekly-plan-builder', category: 'planning',
        name_ar: 'الخطة الأسبوعية', name_en: 'Weekly Plan Builder',
        description_ar: 'إنشاء خطتك الأسبوعية لمادة واحدة أو جميع المواد',
        description_en: 'Create your weekly plan for one or all subjects',
        icon: 'CalendarDays', color: 'bg-amber-600', gradient: 'from-amber-600 to-orange-600',
        route: '/weekly-plan-builder', service_type: 'interactive',
        admin_href: '/admin/educational-services/static-tools/weekly-plan-builder',
        features: [], is_active: true, sort_order: 26,
        requires_auth: false, requires_subscription: false,
        is_new: false, is_popular: true, is_premium: false,
    },
    {
        id: 'academic-calendars', slug: 'academic-calendars', category: 'planning',
        name_ar: 'التقاويم الأكاديمية', name_en: 'Academic Calendars',
        description_ar: 'التقاويم الدراسية وتوزيع الأسابيع والمهام',
        description_en: 'Academic calendars and week/task distribution',
        icon: 'CalendarDays', color: 'bg-teal-600', gradient: 'from-teal-600 to-cyan-700',
        route: '/academic-calendars', service_type: 'interactive',
        admin_href: '/admin/educational-services/static-tools/academic-calendars',
        features: [], is_active: true, sort_order: 27,
        requires_auth: false, requires_subscription: false,
        is_new: false, is_popular: false, is_premium: false,
    },
    {
        id: 'remedial-enrichment-plans', slug: 'remedial-enrichment-plans', category: 'planning',
        name_ar: 'الخطط العلاجية والإثرائية', name_en: 'Remedial & Enrichment Plans',
        description_ar: 'خطط علاجية وإثرائية فردية وجماعية جاهزة للتعبئة',
        description_en: 'Individual and group remedial and enrichment plans ready to fill',
        icon: 'Target', color: 'bg-emerald-600', gradient: 'from-emerald-600 to-green-700',
        route: '/remedial-enrichment-plans', service_type: 'interactive',
        admin_href: '/admin/educational-services/static-tools/remedial-enrichment-plans',
        features: [], is_active: true, sort_order: 28,
        requires_auth: false, requires_subscription: false,
        is_new: false, is_popular: false, is_premium: false,
    },

    // ══════════════════════════════════════════════
    // ── 6. أدوات ومصادر تعليمية ──
    // ══════════════════════════════════════════════
    {
        id: 'worksheets', slug: 'worksheets', category: 'tools',
        name_ar: 'أوراق العمل', name_en: 'Worksheets',
        description_ar: 'إنشاء وإدارة أوراق العمل التعليمية بمساعدة الذكاء الاصطناعي',
        description_en: 'Create and manage educational worksheets with AI assistance',
        icon: 'FileSpreadsheet', color: 'bg-fuchsia-500', gradient: 'from-fuchsia-500 to-pink-600',
        route: '/worksheets', service_type: 'interactive',
        admin_href: '/admin/educational-services/worksheets',
        features: [], is_active: true, sort_order: 29,
        requires_auth: true, requires_subscription: false,
        is_new: true, is_popular: false, is_premium: false,
    },
    {
        id: 'signs-banners', slug: 'signs-banners', category: 'tools',
        name_ar: 'لوحات وبنرات', name_en: 'Signs & Banners',
        description_ar: 'لوحات إرشادية وبنرات للبيئة التعليمية',
        description_en: 'Guidance signs and banners for educational environments',
        icon: 'Layers', color: 'bg-slate-600', gradient: 'from-slate-600 to-gray-700',
        route: '/signs-banners', service_type: 'interactive',
        admin_href: '/admin/educational-services/static-tools/signs-banners',
        features: [], is_active: true, sort_order: 30,
        requires_auth: false, requires_subscription: false,
        is_new: false, is_popular: false, is_premium: false,
    },
    {
        id: 'learning-style-surveys', slug: 'learning-style-surveys', category: 'tools',
        name_ar: 'استبيانات أنماط التعلم', name_en: 'Learning Style Surveys',
        description_ar: 'استبيانات لتحديد أنماط التعلم VARK وتقييم الطلاب',
        description_en: 'VARK learning style surveys and student evaluation',
        icon: 'Brain', color: 'bg-purple-600', gradient: 'from-purple-600 to-violet-700',
        route: '/learning-style-surveys', service_type: 'interactive',
        admin_href: '/admin/educational-services/static-tools/learning-style-surveys',
        features: [], is_active: true, sort_order: 31,
        requires_auth: false, requires_subscription: false,
        is_new: false, is_popular: false, is_premium: false,
    },
    {
        id: 'edu-tools', slug: 'edu-tools', category: 'tools',
        name_ar: 'أدوات مساعدة مجانية', name_en: 'Free Utility Tools',
        description_ar: 'مجموعة أدوات مجانية — QR Code وتحويل صور وحاسبة النسبة الموزونة وتوقيع PDF',
        description_en: 'Free tools — QR Code, image converter, weighted GPA calculator, PDF signing',
        icon: 'Settings', color: 'bg-gray-600', gradient: 'from-gray-600 to-slate-700',
        route: '/edu-tools', service_type: 'interactive',
        admin_href: '/admin/educational-services/static-tools/edu-tools',
        features: [], is_active: true, sort_order: 32,
        requires_auth: false, requires_subscription: false,
        is_new: false, is_popular: true, is_premium: false,
    },
    {
        id: 'my-templates', slug: 'my-templates', category: 'tools',
        name_ar: 'قوالبي المحفوظة', name_en: 'My Saved Templates',
        description_ar: 'إدارة القوالب المحفوظة والمشتراة والمفضلة',
        description_en: 'Manage saved, purchased, and favorite templates',
        icon: 'FolderOpen', color: 'bg-orange-500', gradient: 'from-orange-500 to-amber-500',
        route: '/my-templates', service_type: 'interactive',
        admin_href: '/admin/educational-services/static-tools/my-templates',
        features: [], is_active: true, sort_order: 33,
        requires_auth: true, requires_subscription: false,
        is_new: false, is_popular: true, is_premium: false,
    },

    // ── المساعد الذكي (يُعرض منفصلاً) ──
    {
        id: 'ai-assistant', slug: 'ai-assistant', category: 'ai',
        name_ar: 'المساعد الذكي', name_en: 'Smart Assistant',
        description_ar: 'مساعد ذكي يساعدك في إعداد الخطط والتقارير بالذكاء الاصطناعي',
        description_en: 'AI assistant for preparing plans and reports',
        icon: 'Bot', color: 'bg-indigo-500', gradient: 'from-indigo-500 to-purple-600',
        route: '/ai-assistant', service_type: 'interactive',
        admin_href: '/admin/educational-services/static-tools/ai-assistant',
        features: [], is_active: true, sort_order: 34,
        requires_auth: false, requires_subscription: true,
        is_new: false, is_popular: true, is_premium: true,
    },
];
