/**
 * Default services — single unified list.
 * Every service is dynamic with form editor capabilities.
 * No distinction between "interactive" and "static-tool".
 */
import type { ServiceDefinition } from '@/types';

export const DEFAULT_SERVICES: ServiceDefinition[] = [
    // ── التحليل والاختبارات ──
    {
        id: 'analyses', slug: 'analyses', category: 'analysis',
        name_ar: 'تحليل النتائج', name_en: 'Results Analysis',
        description_ar: 'تحليل نتائج الاختبارات واستخراج التقارير والإحصائيات التفصيلية',
        description_en: 'Analyze test results and generate detailed reports and statistics',
        icon: 'BarChart3', color: 'bg-blue-500', gradient: 'from-blue-500 to-blue-600',
        route: '/analyses', service_type: 'interactive',
        admin_href: '/admin/educational-services/tests',
        features: [], is_active: true, sort_order: 1,
        requires_auth: false, requires_subscription: false,
        is_new: false, is_popular: true, is_premium: false,
    },
    {
        id: 'tests', slug: 'tests', category: 'analysis',
        name_ar: 'الاختبارات', name_en: 'Tests',
        description_ar: 'إنشاء وإدارة الاختبارات وتسجيل درجات الطلاب مع بنك أسئلة شامل',
        description_en: 'Create and manage tests with student grading and question bank',
        icon: 'FileQuestion', color: 'bg-cyan-500', gradient: 'from-cyan-500 to-teal-500',
        route: '/tests', service_type: 'interactive',
        admin_href: '/admin/educational-services/tests',
        features: [], is_active: true, sort_order: 2,
        requires_auth: false, requires_subscription: false,
        is_new: false, is_popular: false, is_premium: false,
    },
    {
        id: 'question-bank', slug: 'question-bank', category: 'analysis',
        name_ar: 'بنك الأسئلة', name_en: 'Question Bank',
        description_ar: 'إدارة بنك أسئلة شامل مصنّف حسب المادة والمستوى',
        description_en: 'Manage a comprehensive question bank by subject and level',
        icon: 'Brain', color: 'bg-rose-500', gradient: 'from-rose-500 to-pink-600',
        route: '/question-bank', service_type: 'interactive',
        admin_href: '/admin/educational-services/question-bank',
        features: [], is_active: true, sort_order: 3,
        requires_auth: false, requires_subscription: false,
        is_new: true, is_popular: false, is_premium: false,
    },

    // ── الشهادات ──
    {
        id: 'certificates', slug: 'certificates', category: 'documents',
        name_ar: 'الشهادات والتقدير', name_en: 'Certificates & Appreciation',
        description_ar: 'إنشاء شهادات الشكر والتقدير والتخرج بتصاميم احترافية',
        description_en: 'Create appreciation and graduation certificates with professional designs',
        icon: 'Award', color: 'bg-amber-500', gradient: 'from-amber-500 to-orange-500',
        route: '/certificates', service_type: 'interactive',
        admin_href: '/admin/educational-services/certificates',
        features: [], is_active: true, sort_order: 4,
        requires_auth: false, requires_subscription: false,
        is_new: false, is_popular: true, is_premium: false,
    },

    // ── التخطيط والتوزيعات ──
    {
        id: 'plans', slug: 'plans', category: 'planning',
        name_ar: 'الخطط التعليمية', name_en: 'Educational Plans',
        description_ar: 'إنشاء الخطط العلاجية والإثرائية وتوزيع المنهج',
        description_en: 'Create remedial and enrichment plans with curriculum distribution',
        icon: 'ClipboardList', color: 'bg-green-500', gradient: 'from-green-500 to-emerald-500',
        route: '/plans', service_type: 'interactive',
        admin_href: '/admin/educational-services/plans',
        features: [], is_active: true, sort_order: 5,
        requires_auth: false, requires_subscription: false,
        is_new: false, is_popular: true, is_premium: false,
    },
    {
        id: 'distributions', slug: 'distributions', category: 'planning',
        name_ar: 'التوزيعات', name_en: 'Distributions',
        description_ar: 'إعداد توزيعات المنهج الأسبوعية والشهرية والفصلية',
        description_en: 'Prepare weekly, monthly, and semester curriculum distributions',
        icon: 'CalendarDays', color: 'bg-teal-500', gradient: 'from-teal-500 to-cyan-500',
        route: '/distributions', service_type: 'interactive',
        admin_href: '/admin/educational-services/distributions',
        features: [], is_active: true, sort_order: 6,
        requires_auth: false, requires_subscription: false,
        is_new: true, is_popular: false, is_premium: false,
    },
    {
        id: 'curriculum', slug: 'curriculum', category: 'planning',
        name_ar: 'المناهج الدراسية', name_en: 'Curriculum',
        description_ar: 'إدارة وتنظيم المناهج الدراسية والخطط الفصلية',
        description_en: 'Manage and organize curricula and semester plans',
        icon: 'GraduationCap', color: 'bg-teal-500', gradient: 'from-teal-500 to-cyan-600',
        route: '/curriculum', service_type: 'interactive',
        admin_href: '/admin/educational-services/curriculum',
        features: [], is_active: true, sort_order: 7,
        requires_auth: false, requires_subscription: false,
        is_new: false, is_popular: false, is_premium: false,
    },
    {
        id: 'weekly-plan-builder', slug: 'weekly-plan-builder', category: 'planning',
        name_ar: 'الخطة الأسبوعية', name_en: 'Weekly Plan Builder',
        description_ar: 'إنشاء خطتك الأسبوعية لمادة واحدة أو جميع المواد',
        description_en: 'Create your weekly plan for one or all subjects',
        icon: 'CalendarDays', color: 'bg-amber-600', gradient: 'from-amber-600 to-orange-600',
        route: '/weekly-plan-builder', service_type: 'interactive',
        admin_href: '/admin/educational-services/static-tools/weekly-plan-builder',
        features: [], is_active: true, sort_order: 8,
        requires_auth: false, requires_subscription: false,
        is_new: false, is_popular: true, is_premium: false,
    },
    {
        id: 'academic-calendars', slug: 'academic-calendars', category: 'planning',
        name_ar: 'التقاويم الأكاديمية', name_en: 'Academic Calendars',
        description_ar: 'التقاويم الدراسية وتوزيع الأسابيع والمهام',
        description_en: 'Academic calendars and week/task distribution',
        icon: 'CalendarDays', color: 'bg-teal-600', gradient: 'from-teal-600 to-cyan-700',
        route: '/academic-calendars', service_type: 'interactive',
        admin_href: '/admin/educational-services/static-tools/academic-calendars',
        features: [], is_active: true, sort_order: 9,
        requires_auth: false, requires_subscription: false,
        is_new: false, is_popular: false, is_premium: false,
    },

    // ── السجلات والتوثيق ──
    {
        id: 'achievements', slug: 'achievements', category: 'records',
        name_ar: 'توثيق الإنجازات', name_en: 'Document Achievements',
        description_ar: 'توثيق الإنجازات اليومية والأسبوعية والشهرية',
        description_en: 'Document daily, weekly, and monthly achievements',
        icon: 'Trophy', color: 'bg-purple-500', gradient: 'from-purple-500 to-violet-500',
        route: '/achievements', service_type: 'interactive',
        admin_href: '/admin/educational-services/achievements',
        features: [], is_active: true, sort_order: 10,
        requires_auth: false, requires_subscription: false,
        is_new: false, is_popular: false, is_premium: false,
    },
    {
        id: 'knowledge-production', slug: 'knowledge-production', category: 'records',
        name_ar: 'الإنتاج المعرفي', name_en: 'Knowledge Production',
        description_ar: 'توثيق الإنتاج المعرفي من أبحاث ومقالات وأوراق عمل ومبادرات',
        description_en: 'Document knowledge production including research, articles, and initiatives',
        icon: 'Lightbulb', color: 'bg-yellow-500', gradient: 'from-yellow-500 to-amber-500',
        route: '/knowledge-production', service_type: 'interactive',
        admin_href: '/admin/educational-services/knowledge-production',
        features: [], is_active: true, sort_order: 11,
        requires_auth: false, requires_subscription: false,
        is_new: true, is_popular: false, is_premium: false,
    },
    {
        id: 'follow-up-log', slug: 'follow-up-log', category: 'records',
        name_ar: 'سجل المتابعة', name_en: 'Follow-up Log',
        description_ar: 'سجل متابعة شامل لتوثيق الزيارات والتوصيات',
        description_en: 'Comprehensive follow-up log for visits and recommendations',
        icon: 'ScrollText', color: 'bg-emerald-500', gradient: 'from-emerald-500 to-green-500',
        route: '/follow-up-log', service_type: 'interactive',
        admin_href: '/admin/educational-services/follow-up-log',
        features: [], is_active: true, sort_order: 12,
        requires_auth: false, requires_subscription: false,
        is_new: true, is_popular: false, is_premium: false,
    },
    {
        id: 'work-evidence', slug: 'work-evidence', category: 'records',
        name_ar: 'شواهد الأداء الوظيفي', name_en: 'Performance Evidence',
        description_ar: 'توثيق شواهد الأداء الوظيفي الـ 11 بند',
        description_en: 'Document the 11 approved performance evidence items',
        icon: 'ClipboardCheck', color: 'bg-sky-500', gradient: 'from-sky-500 to-blue-500',
        route: '/work-evidence', service_type: 'interactive',
        admin_href: '/admin/educational-services/work-evidence',
        features: [], is_active: true, sort_order: 13,
        requires_auth: false, requires_subscription: false,
        is_new: true, is_popular: false, is_premium: false,
    },
    {
        id: 'portfolio', slug: 'portfolio', category: 'records',
        name_ar: 'ملف الإنجاز', name_en: 'Portfolio',
        description_ar: 'ملف إنجاز رقمي شامل لجمع الشهادات والإنجازات والتدريبات',
        description_en: 'Comprehensive digital portfolio for certificates and achievements',
        icon: 'FolderArchive', color: 'bg-rose-500', gradient: 'from-rose-500 to-pink-500',
        route: '/portfolio', service_type: 'interactive',
        admin_href: '/admin/educational-services/static-tools/portfolio',
        features: [], is_active: true, sort_order: 14,
        requires_auth: false, requires_subscription: false,
        is_new: true, is_popular: true, is_premium: false,
    },

    // ── النماذج وأوراق العمل ──
    {
        id: 'documentation-forms', slug: 'documentation-forms', category: 'documents',
        name_ar: 'نماذج وتقارير التوثيق', name_en: 'Documentation Forms',
        description_ar: 'نماذج توثيق احترافية جاهزة للتعبئة والطباعة',
        description_en: 'Professional documentation forms ready to fill and print',
        icon: 'ClipboardList', color: 'bg-blue-700', gradient: 'from-blue-600 to-blue-700',
        route: '/documentation-forms', service_type: 'interactive',
        admin_href: '/admin/educational-services/static-tools/documentation-forms',
        features: [], is_active: true, sort_order: 15,
        requires_auth: false, requires_subscription: false,
        is_new: false, is_popular: true, is_premium: false,
    },
    {
        id: 'performance-evidence-forms', slug: 'performance-evidence-forms', category: 'documents',
        name_ar: 'شواهد الأداء الجاهزة', name_en: 'Performance Evidence Forms',
        description_ar: 'نماذج شواهد أداء وظيفي جاهزة للتعبئة',
        description_en: 'Ready-to-fill performance evidence forms',
        icon: 'ClipboardCheck', color: 'bg-violet-600', gradient: 'from-violet-600 to-purple-700',
        route: '/performance-evidence-forms', service_type: 'interactive',
        admin_href: '/admin/educational-services/static-tools/performance-evidence-forms',
        features: [], is_active: true, sort_order: 16,
        requires_auth: false, requires_subscription: false,
        is_new: true, is_popular: false, is_premium: false,
    },
    {
        id: 'teacher-evaluation-forms', slug: 'teacher-evaluation-forms', category: 'documents',
        name_ar: 'عناصر تقييم المعلمين', name_en: 'Teacher Evaluation Forms',
        description_ar: 'نماذج مفرغة لعناصر تقييم الأداء الوظيفي للمعلمين',
        description_en: 'Blank forms for teacher performance evaluation elements',
        icon: 'GraduationCap', color: 'bg-emerald-600', gradient: 'from-emerald-600 to-green-700',
        route: '/teacher-evaluation-forms', service_type: 'interactive',
        admin_href: '/admin/educational-services/static-tools/teacher-evaluation-forms',
        features: [], is_active: true, sort_order: 17,
        requires_auth: false, requires_subscription: false,
        is_new: false, is_popular: false, is_premium: false,
    },
    {
        id: 'worksheets', slug: 'worksheets', category: 'documents',
        name_ar: 'أوراق العمل', name_en: 'Worksheets',
        description_ar: 'إنشاء وإدارة أوراق العمل التعليمية بمساعدة الذكاء الاصطناعي',
        description_en: 'Create and manage educational worksheets with AI assistance',
        icon: 'FileSpreadsheet', color: 'bg-fuchsia-500', gradient: 'from-fuchsia-500 to-pink-600',
        route: '/worksheets', service_type: 'interactive',
        admin_href: '/admin/educational-services/worksheets',
        features: [], is_active: true, sort_order: 18,
        requires_auth: false, requires_subscription: false,
        is_new: true, is_popular: false, is_premium: false,
    },

    // ── المجتمع والتواصل ──
    {
        id: 'professional-community', slug: 'professional-community', category: 'community',
        name_ar: 'المجتمع المهني', name_en: 'Professional Community',
        description_ar: 'استمارات وتقارير مجتمعات التعلم المهنية',
        description_en: 'Professional learning community forms and reports',
        icon: 'Users', color: 'bg-indigo-600', gradient: 'from-indigo-600 to-blue-700',
        route: '/professional-community', service_type: 'interactive',
        admin_href: '/admin/educational-services/static-tools/professional-community',
        features: [], is_active: true, sort_order: 19,
        requires_auth: false, requires_subscription: false,
        is_new: false, is_popular: false, is_premium: false,
    },
    {
        id: 'parents-interaction', slug: 'parents-interaction', category: 'community',
        name_ar: 'تفاعل أولياء الأمور', name_en: 'Parents Interaction',
        description_ar: 'نماذج التواصل مع أولياء الأمور والاجتماعات',
        description_en: 'Parent communication forms and meeting reports',
        icon: 'Users', color: 'bg-sky-600', gradient: 'from-sky-600 to-blue-700',
        route: '/parents-interaction', service_type: 'interactive',
        admin_href: '/admin/educational-services/static-tools/parents-interaction',
        features: [], is_active: true, sort_order: 20,
        requires_auth: false, requires_subscription: false,
        is_new: false, is_popular: false, is_premium: false,
    },
    {
        id: 'school-initiatives', slug: 'school-initiatives', category: 'community',
        name_ar: 'المبادرات المدرسية', name_en: 'School Initiatives',
        description_ar: 'نماذج توثيق المبادرات المدرسية والبرامج التعليمية',
        description_en: 'School initiatives and educational programs documentation',
        icon: 'Sparkles', color: 'bg-pink-600', gradient: 'from-pink-600 to-rose-700',
        route: '/school-initiatives', service_type: 'interactive',
        admin_href: '/admin/educational-services/static-tools/school-initiatives',
        features: [], is_active: true, sort_order: 21,
        requires_auth: false, requires_subscription: false,
        is_new: false, is_popular: false, is_premium: false,
    },

    // ── البيئة والتحسين ──
    {
        id: 'school-environment', slug: 'school-environment', category: 'environment',
        name_ar: 'البيئة المدرسية', name_en: 'School Environment',
        description_ar: 'نماذج تهيئة البيئة المدرسية للبرامج والأنشطة',
        description_en: 'School environment preparation forms',
        icon: 'BookOpen', color: 'bg-lime-600', gradient: 'from-lime-600 to-green-700',
        route: '/school-environment', service_type: 'interactive',
        admin_href: '/admin/educational-services/static-tools/school-environment',
        features: [], is_active: true, sort_order: 22,
        requires_auth: false, requires_subscription: false,
        is_new: false, is_popular: false, is_premium: false,
    },
    {
        id: 'signs-banners', slug: 'signs-banners', category: 'environment',
        name_ar: 'لوحات وبنرات', name_en: 'Signs & Banners',
        description_ar: 'لوحات إرشادية وبنرات للبيئة التعليمية',
        description_en: 'Guidance signs and banners for educational environments',
        icon: 'Layers', color: 'bg-slate-600', gradient: 'from-slate-600 to-gray-700',
        route: '/signs-banners', service_type: 'interactive',
        admin_href: '/admin/educational-services/static-tools/signs-banners',
        features: [], is_active: true, sort_order: 23,
        requires_auth: false, requires_subscription: false,
        is_new: false, is_popular: false, is_premium: false,
    },
    {
        id: 'improve-results', slug: 'improve-results', category: 'environment',
        name_ar: 'تحسين النتائج', name_en: 'Improve Results',
        description_ar: 'أدوات وخطط لتحسين نتائج الطلاب',
        description_en: 'Tools and plans for improving student results',
        icon: 'TrendingUp', color: 'bg-green-600', gradient: 'from-green-600 to-emerald-700',
        route: '/improve-results', service_type: 'interactive',
        admin_href: '/admin/educational-services/static-tools/improve-results',
        features: [], is_active: true, sort_order: 24,
        requires_auth: false, requires_subscription: false,
        is_new: false, is_popular: false, is_premium: false,
    },

    // ── الاستبيانات ──
    {
        id: 'learning-style-surveys', slug: 'learning-style-surveys', category: 'surveys',
        name_ar: 'استبيانات أنماط التعلم', name_en: 'Learning Style Surveys',
        description_ar: 'استبيانات لتحديد أنماط التعلم وتقييم الطلاب',
        description_en: 'Surveys for identifying learning styles and student evaluation',
        icon: 'Brain', color: 'bg-purple-600', gradient: 'from-purple-600 to-violet-700',
        route: '/learning-style-surveys', service_type: 'interactive',
        admin_href: '/admin/educational-services/static-tools/learning-style-surveys',
        features: [], is_active: true, sort_order: 25,
        requires_auth: false, requires_subscription: false,
        is_new: false, is_popular: false, is_premium: false,
    },

    // ── الأدوات الذكية ──
    {
        id: 'ai-assistant', slug: 'ai-assistant', category: 'ai',
        name_ar: 'المساعد الذكي', name_en: 'Smart Assistant',
        description_ar: 'مساعد ذكي يساعدك في إعداد الخطط والتقارير بالذكاء الاصطناعي',
        description_en: 'AI assistant for preparing plans and reports',
        icon: 'Bot', color: 'bg-indigo-500', gradient: 'from-indigo-500 to-purple-600',
        route: '/ai-assistant', service_type: 'interactive',
        admin_href: '/admin/educational-services/static-tools/ai-assistant',
        features: [], is_active: true, sort_order: 26,
        requires_auth: false, requires_subscription: true,
        is_new: false, is_popular: true, is_premium: true,
    },
    {
        id: 'my-templates', slug: 'my-templates', category: 'ai',
        name_ar: 'قوالبي المحفوظة', name_en: 'My Saved Templates',
        description_ar: 'إدارة القوالب المحفوظة والمشتراة والمفضلة',
        description_en: 'Manage saved, purchased, and favorite templates',
        icon: 'FolderOpen', color: 'bg-orange-500', gradient: 'from-orange-500 to-amber-500',
        route: '/my-templates', service_type: 'interactive',
        admin_href: '/admin/educational-services/static-tools/my-templates',
        features: [], is_active: true, sort_order: 27,
        requires_auth: true, requires_subscription: false,
        is_new: false, is_popular: true, is_premium: false,
    },
];
