/**
 * SERS Seed Data - بيانات أولية شاملة
 * 13 تصنيف رئيسي + 102 خدمة تعليمية
 * 
 * هذه البيانات تُستخدم كـ:
 * 1. Fallback عندما لا تتوفر بيانات في Firestore
 * 2. بيانات أولية يمكن تحميلها إلى Firestore عبر لوحة الإدارة
 * 
 * ملاحظة: جميع هذه البيانات يمكن تعديلها/حذفها/إضافة المزيد من لوحة الإدارة
 */

// ============================================
// التصنيفات الرئيسية (13 تصنيف)
// ============================================

export const SEED_CATEGORIES: any[] = [
  {
    name: 'شواهد الأداء الوظيفي',
    slug: 'performance-evidence',
    description: 'توثيق شواهد الأداء الوظيفي لجميع الوظائف التعليمية وفق معايير وزارة التعليم',
    icon: 'ClipboardCheck',
    color: '#2563EB',
    order: 1,
    is_active: true,
    services_count: 8,
  },
  {
    name: 'ملفات الإنجاز',
    slug: 'portfolios',
    description: 'ملفات إنجاز إلكترونية شاملة لتوثيق الأعمال والإنجازات المهنية لجميع الكوادر التعليمية',
    icon: 'FolderOpen',
    color: '#7C3AED',
    order: 2,
    is_active: true,
    services_count: 6,
  },
  {
    name: 'التقارير والتحليلات',
    slug: 'reports-analytics',
    description: 'تقارير تحليلية شاملة للنتائج والأداء الأكاديمي مع رسوم بيانية تفاعلية',
    icon: 'BarChart3',
    color: '#059669',
    order: 3,
    is_active: true,
    services_count: 11,
  },
  {
    name: 'الخطط التعليمية',
    slug: 'educational-plans',
    description: 'خطط علاجية وإثرائية وتطويرية لجميع المراحل الدراسية',
    icon: 'FileText',
    color: '#DC2626',
    order: 4,
    is_active: true,
    services_count: 9,
  },
  {
    name: 'الشهادات والتقدير',
    slug: 'certificates-awards',
    description: 'شهادات شكر وتقدير وحضور ومشاركة بتصاميم احترافية قابلة للتخصيص',
    icon: 'Award',
    color: '#D97706',
    order: 5,
    is_active: true,
    services_count: 9,
  },
  {
    name: 'السجلات المدرسية',
    slug: 'school-records',
    description: 'جميع السجلات الإدارية والتعليمية المطلوبة في المدارس',
    icon: 'BookOpen',
    color: '#0891B2',
    order: 6,
    is_active: true,
    services_count: 13,
  },
  {
    name: 'ورش العمل والتدريب',
    slug: 'workshops-training',
    description: 'نماذج وتقارير ورش العمل والبرامج التدريبية المهنية',
    icon: 'Users',
    color: '#9333EA',
    order: 7,
    is_active: true,
    services_count: 6,
  },
  {
    name: 'المبادرات والمشاريع',
    slug: 'initiatives-projects',
    description: 'نماذج توثيق المبادرات التعليمية والمشاريع المدرسية والممارسات المهنية',
    icon: 'Lightbulb',
    color: '#EA580C',
    order: 8,
    is_active: true,
    services_count: 6,
  },
  {
    name: 'المجتمعات المهنية',
    slug: 'professional-communities',
    description: 'نماذج وتقارير مجتمعات التعلم المهنية وبحث الدرس والبحوث الإجرائية',
    icon: 'Network',
    color: '#4F46E5',
    order: 9,
    is_active: true,
    services_count: 6,
  },
  {
    name: 'التحضير والتخطيط',
    slug: 'lesson-planning',
    description: 'أدوات تحضير الدروس والتخطيط التعليمي وتوزيع المناهج',
    icon: 'PenTool',
    color: '#0D9488',
    order: 10,
    is_active: true,
    services_count: 6,
  },
  {
    name: 'الاختبارات والتقويم',
    slug: 'tests-assessment',
    description: 'أدوات إعداد الاختبارات والتقويم المستمر وتحليل النتائج',
    icon: 'CheckSquare',
    color: '#BE185D',
    order: 11,
    is_active: true,
    services_count: 7,
  },
  {
    name: 'الكشوفات والبيانات',
    slug: 'data-sheets',
    description: 'كشوفات الطلاب والبيانات الإدارية والجداول المدرسية',
    icon: 'Table',
    color: '#65A30D',
    order: 12,
    is_active: true,
    services_count: 7,
  },
  {
    name: 'الخطابات والمراسلات',
    slug: 'letters-correspondence',
    description: 'نماذج خطابات رسمية ومراسلات إدارية جاهزة للتعبئة',
    icon: 'Mail',
    color: '#6366F1',
    order: 13,
    is_active: true,
    services_count: 8,
  },
];

// ============================================
// الخدمات التعليمية (102 خدمة)
// ============================================

export const SEED_SERVICES: any[] = [
  // ========================================
  // 1. شواهد الأداء الوظيفي (8 خدمات)
  // ========================================
  {
    title: 'شواهد الأداء الوظيفي للمعلم/ة',
    slug: 'teacher-performance-evidence',
    description: 'ملف شامل لتوثيق شواهد الأداء الوظيفي للمعلم والمعلمة وفق معايير وزارة التعليم المعتمدة، يتضمن 11 بنداً أساسياً تشمل أداء الواجبات الوظيفية، التفاعل مع المجتمع المهني، استراتيجيات التدريس الفعّالة، تحليل نتائج المتعلمين، والتقويم المستمر.',
    short_description: 'توثيق شواهد الأداء الوظيفي للمعلم/ة - 11 بنداً وفق معايير الوزارة',
    category: 'performance-evidence',
    icon: 'ClipboardCheck',
    price: 0,
    is_free: true,
    is_popular: true,
    is_new: false,
    status: 'active',
    features: [
      'أداء الواجبات الوظيفية',
      'التفاعل مع المجتمع المهني',
      'التفاعل مع أولياء الأمور والمجتمع',
      'استخدام استراتيجيات التدريس الفعّالة',
      'تحسين نتائج المتعلمين',
      'إعداد خطة التعلم',
      'توظيف التقنية في التعليم',
      'تهيئة بيئة تعليمية محفزة',
      'الإدارة الصفية الفعّالة',
      'تحليل نتائج المتعلمين',
      'التقويم المستمر',
    ],
    tags: ['شواهد', 'أداء وظيفي', 'معلم', 'معلمة', 'تقييم'],
  },
  {
    title: 'شواهد الأداء الوظيفي للموجه/ة الطلابي/ة',
    slug: 'counselor-performance-evidence',
    description: 'ملف شامل لتوثيق شواهد الأداء الوظيفي للموجه والموجهة الطلابية، يتضمن بنوداً متخصصة تشمل التدخلات النفسية والاجتماعية، تعزيز الانضباط، برامج الدعم، التخطيط المهني والتعليمي للطلاب.',
    short_description: 'توثيق شواهد الأداء الوظيفي للموجه/ة الطلابي/ة',
    category: 'performance-evidence',
    icon: 'UserCheck',
    price: 0,
    is_free: true,
    is_popular: true,
    is_new: false,
    status: 'active',
    features: [
      'أداء الواجبات الوظيفية',
      'التفاعل مع المجتمع المهني',
      'التفاعل مع أولياء الأمور',
      'تقديم التدخلات المناسبة لتعزيز الانضباط',
      'تقديم برامج تربوية لتعزيز دافعية الطلبة',
      'تصنيف الحالات وتقديم برامج الدعم',
      'تقديم التدخلات النفسية والاجتماعية',
      'تعزيز التفوق الدراسي',
      'توعية المتعلمين بقواعد السلوك والمواظبة',
      'إعداد خطة لبرامج التوجيه الطلابي',
      'تعزيز القيم والسلوكيات',
      'مساعدة المتعلمين على التخطيط المهني',
      'تدخلات تربوية للمتأخرين دراسياً',
    ],
    tags: ['شواهد', 'أداء وظيفي', 'موجه طلابي', 'إرشاد'],
  },
  {
    title: 'شواهد الأداء الوظيفي لمدير/ة المدرسة',
    slug: 'principal-performance-evidence',
    description: 'ملف شامل لتوثيق شواهد الأداء الوظيفي لمدير ومديرة المدرسة، يتضمن بنود القيادة المدرسية، إدارة الموارد، تطوير بيئة التعلم، والتخطيط الاستراتيجي.',
    short_description: 'توثيق شواهد الأداء الوظيفي لمدير/ة المدرسة',
    category: 'performance-evidence',
    icon: 'Building',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['القيادة المدرسية', 'إدارة الموارد البشرية', 'تطوير بيئة التعلم', 'التخطيط الاستراتيجي', 'إدارة الميزانية', 'العلاقات المجتمعية', 'الإشراف التربوي', 'تحسين الأداء المدرسي'],
    tags: ['شواهد', 'أداء وظيفي', 'مدير', 'مديرة', 'قيادة'],
  },
  {
    title: 'شواهد الأداء الوظيفي للموجه/ة الصحي/ة',
    slug: 'health-counselor-performance-evidence',
    description: 'ملف شامل لتوثيق شواهد الأداء الوظيفي للموجه والموجهة الصحية في المدارس.',
    short_description: 'توثيق شواهد الأداء الوظيفي للموجه/ة الصحي/ة',
    category: 'performance-evidence',
    icon: 'Heart',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: true,
    status: 'active',
    features: ['التثقيف الصحي', 'الإسعافات الأولية', 'متابعة الحالات الصحية', 'برامج التوعية', 'التقارير الصحية', 'بيئة مدرسية صحية'],
    tags: ['شواهد', 'أداء وظيفي', 'موجه صحي', 'صحة مدرسية'],
  },
  {
    title: 'شواهد الأداء الوظيفي لمعلمة رياض الأطفال',
    slug: 'kindergarten-teacher-performance-evidence',
    description: 'ملف شامل لتوثيق شواهد الأداء الوظيفي لمعلمة رياض الأطفال وفق معايير الطفولة المبكرة.',
    short_description: 'توثيق شواهد الأداء الوظيفي لمعلمة رياض الأطفال',
    category: 'performance-evidence',
    icon: 'Baby',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: true,
    status: 'active',
    features: ['رعاية الطفولة المبكرة', 'التعلم باللعب', 'تنمية المهارات الحركية', 'التطور اللغوي', 'التفاعل الاجتماعي', 'بيئة تعلم آمنة'],
    tags: ['شواهد', 'أداء وظيفي', 'رياض أطفال', 'طفولة مبكرة'],
  },
  {
    title: 'شواهد الأداء الوظيفي لوكيل/ة المدرسة',
    slug: 'vice-principal-performance-evidence',
    description: 'ملف شامل لتوثيق شواهد الأداء الوظيفي لوكيل ووكيلة المدرسة.',
    short_description: 'توثيق شواهد الأداء الوظيفي لوكيل/ة المدرسة',
    category: 'performance-evidence',
    icon: 'UserCog',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['الإشراف الإداري', 'متابعة الحضور والغياب', 'تنظيم الجداول', 'إدارة الاختبارات', 'التواصل مع أولياء الأمور', 'الإشراف على الأنشطة'],
    tags: ['شواهد', 'أداء وظيفي', 'وكيل', 'وكيلة'],
  },
  {
    title: 'شواهد الأداء الوظيفي لأمين/ة المصادر',
    slug: 'librarian-performance-evidence',
    description: 'ملف شامل لتوثيق شواهد الأداء الوظيفي لأمين وأمينة مصادر التعلم.',
    short_description: 'توثيق شواهد الأداء الوظيفي لأمين/ة المصادر',
    category: 'performance-evidence',
    icon: 'Library',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['إدارة مركز المصادر', 'تنظيم المكتبة', 'دعم البحث العلمي', 'برامج تشجيع القراءة', 'التقنيات التعليمية', 'خدمات المعلومات'],
    tags: ['شواهد', 'أداء وظيفي', 'أمين مصادر', 'مكتبة'],
  },
  {
    title: 'شواهد الأداء الوظيفي للمشرف/ة التربوي/ة',
    slug: 'supervisor-performance-evidence',
    description: 'ملف شامل لتوثيق شواهد الأداء الوظيفي للمشرف والمشرفة التربوية.',
    short_description: 'توثيق شواهد الأداء الوظيفي للمشرف/ة التربوي/ة',
    category: 'performance-evidence',
    icon: 'Eye',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['الإشراف التربوي', 'تطوير المعلمين', 'الزيارات الصفية', 'تحليل الممارسات', 'التدريب المهني', 'تقييم الأداء'],
    tags: ['شواهد', 'أداء وظيفي', 'مشرف تربوي', 'إشراف'],
  },

  // ========================================
  // 2. ملفات الإنجاز (6 خدمات)
  // ========================================
  {
    title: 'ملف إنجاز المعلم/ة الإلكتروني',
    slug: 'teacher-portfolio',
    description: 'ملف إنجاز إلكتروني شامل للمعلم والمعلمة يتضمن السيرة الذاتية، الرؤية والرسالة، الشهادات والدورات، خطة التطوير المهني، نماذج الأعمال، والمبادرات.',
    short_description: 'ملف إنجاز إلكتروني شامل للمعلم/ة',
    category: 'portfolios',
    icon: 'FolderOpen',
    price: 0,
    is_free: true,
    is_popular: true,
    is_new: false,
    status: 'active',
    features: ['السيرة الذاتية', 'الرؤية والرسالة', 'الشهادات والدورات', 'خطة التطوير المهني', 'نماذج الأعمال', 'شهادات الشكر', 'المبادرات', 'الأنشطة اللاصفية'],
    tags: ['ملف إنجاز', 'معلم', 'معلمة', 'بورتفوليو'],
  },
  {
    title: 'ملف إنجاز مدير/ة المدرسة',
    slug: 'principal-portfolio',
    description: 'ملف إنجاز إلكتروني شامل لمدير ومديرة المدرسة يوثق الإنجازات القيادية والإدارية.',
    short_description: 'ملف إنجاز إلكتروني لمدير/ة المدرسة',
    category: 'portfolios',
    icon: 'Briefcase',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['الإنجازات القيادية', 'خطط التطوير', 'المشاريع المدرسية', 'التقارير السنوية', 'الجوائز والتكريمات'],
    tags: ['ملف إنجاز', 'مدير', 'مديرة', 'قيادة'],
  },
  {
    title: 'ملف إنجاز الموجه/ة الطلابي/ة',
    slug: 'counselor-portfolio',
    description: 'ملف إنجاز إلكتروني شامل للموجه والموجهة الطلابية.',
    short_description: 'ملف إنجاز إلكتروني للموجه/ة الطلابي/ة',
    category: 'portfolios',
    icon: 'Heart',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['البرامج الإرشادية', 'الحالات المعالجة', 'برامج التوعية', 'التقارير الدورية', 'الشراكات المجتمعية'],
    tags: ['ملف إنجاز', 'موجه طلابي', 'إرشاد'],
  },
  {
    title: 'ملف إنجاز المشرف/ة التربوي/ة',
    slug: 'supervisor-portfolio',
    description: 'ملف إنجاز إلكتروني شامل للمشرف والمشرفة التربوية.',
    short_description: 'ملف إنجاز إلكتروني للمشرف/ة التربوي/ة',
    category: 'portfolios',
    icon: 'Eye',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['الزيارات الإشرافية', 'تطوير المعلمين', 'البرامج التدريبية', 'التقارير الإشرافية', 'الممارسات المتميزة'],
    tags: ['ملف إنجاز', 'مشرف تربوي', 'إشراف'],
  },
  {
    title: 'ملف إنجاز وكيل/ة المدرسة',
    slug: 'vice-principal-portfolio',
    description: 'ملف إنجاز إلكتروني شامل لوكيل ووكيلة المدرسة.',
    short_description: 'ملف إنجاز إلكتروني لوكيل/ة المدرسة',
    category: 'portfolios',
    icon: 'UserCog',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['الإنجازات الإدارية', 'تنظيم العمل المدرسي', 'متابعة الأداء', 'التقارير الدورية'],
    tags: ['ملف إنجاز', 'وكيل', 'وكيلة'],
  },
  {
    title: 'ملف إنجاز الطالب/ة',
    slug: 'student-portfolio',
    description: 'ملف إنجاز إلكتروني للطالب والطالبة يوثق المسيرة الأكاديمية والأنشطة والإنجازات.',
    short_description: 'ملف إنجاز إلكتروني للطالب/ة',
    category: 'portfolios',
    icon: 'GraduationCap',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: true,
    status: 'active',
    features: ['السجل الأكاديمي', 'الأنشطة والمشاركات', 'الإنجازات والجوائز', 'المهارات المكتسبة', 'الأعمال التطوعية'],
    tags: ['ملف إنجاز', 'طالب', 'طالبة'],
  },

  // ========================================
  // 3. التقارير والتحليلات (11 خدمة)
  // ========================================
  {
    title: 'تقرير تحليل نتائج الاختبارات',
    slug: 'test-results-analysis',
    description: 'تقرير تحليلي شامل لنتائج الاختبارات مع رسوم بيانية تفاعلية ومقارنات بين الفصول والمواد.',
    short_description: 'تحليل شامل لنتائج الاختبارات مع رسوم بيانية',
    category: 'reports-analytics',
    icon: 'BarChart3',
    price: 0,
    is_free: true,
    is_popular: true,
    is_new: false,
    status: 'active',
    features: ['تحليل إحصائي', 'رسوم بيانية', 'مقارنة بين الفصول', 'تصنيف المستويات', 'توصيات تحسين'],
    tags: ['تحليل', 'نتائج', 'اختبارات', 'إحصائيات'],
  },
  {
    title: 'تقرير تحليل نتائج الفترات',
    slug: 'period-results-analysis',
    description: 'تقرير تحليلي لنتائج الفترات الدراسية مع متابعة تقدم الطلاب.',
    short_description: 'تحليل نتائج الفترات الدراسية',
    category: 'reports-analytics',
    icon: 'TrendingUp',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['تحليل الفترات', 'متابعة التقدم', 'مقارنة الفترات', 'رسوم بيانية'],
    tags: ['تحليل', 'فترات', 'نتائج'],
  },
  {
    title: 'تقرير المقارنة بين الفصول الدراسية',
    slug: 'semester-comparison-report',
    description: 'تقرير مقارنة شامل بين الفصول الدراسية لتتبع تطور الأداء.',
    short_description: 'مقارنة أداء الفصول الدراسية',
    category: 'reports-analytics',
    icon: 'GitCompare',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['مقارنة الفصول', 'تتبع التطور', 'تحليل الفروقات', 'توصيات'],
    tags: ['مقارنة', 'فصول', 'تقرير'],
  },
  {
    title: 'تقرير الفاقد التعليمي',
    slug: 'learning-loss-report',
    description: 'تقرير شامل لتحديد الفاقد التعليمي لجميع المواد مع خطط العلاج المقترحة.',
    short_description: 'تحديد الفاقد التعليمي وخطط العلاج',
    category: 'reports-analytics',
    icon: 'AlertTriangle',
    price: 0,
    is_free: true,
    is_popular: true,
    is_new: false,
    status: 'active',
    features: ['تحديد الفاقد', 'تحليل المهارات', 'خطط علاجية', 'متابعة التحسن'],
    tags: ['فاقد تعليمي', 'علاج', 'مهارات'],
  },
  {
    title: 'تقرير أداء المعلمين',
    slug: 'teachers-performance-report',
    description: 'تقرير تحليلي لأداء المعلمين بناءً على نتائج الطلاب والزيارات الصفية.',
    short_description: 'تحليل أداء المعلمين',
    category: 'reports-analytics',
    icon: 'UserCheck',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['تقييم الأداء', 'نتائج الطلاب', 'الزيارات الصفية', 'خطط التطوير'],
    tags: ['أداء', 'معلمين', 'تقييم'],
  },
  {
    title: 'تقرير الحضور والغياب',
    slug: 'attendance-report',
    description: 'تقرير شامل للحضور والغياب مع إحصائيات ورسوم بيانية.',
    short_description: 'إحصائيات الحضور والغياب',
    category: 'reports-analytics',
    icon: 'CalendarCheck',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['إحصائيات الحضور', 'نسب الغياب', 'تقارير شهرية', 'إنذارات'],
    tags: ['حضور', 'غياب', 'تقرير'],
  },
  {
    title: 'تقرير السلوك والمواظبة',
    slug: 'behavior-report',
    description: 'تقرير شامل لسلوك الطلاب ومواظبتهم مع تصنيف المخالفات.',
    short_description: 'تقرير سلوك الطلاب والمواظبة',
    category: 'reports-analytics',
    icon: 'Shield',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['تصنيف المخالفات', 'متابعة السلوك', 'الإجراءات المتخذة', 'تقارير دورية'],
    tags: ['سلوك', 'مواظبة', 'انضباط'],
  },
  {
    title: 'تقرير الأنشطة المدرسية',
    slug: 'activities-report',
    description: 'تقرير توثيقي شامل للأنشطة المدرسية المنفذة خلال العام.',
    short_description: 'توثيق الأنشطة المدرسية',
    category: 'reports-analytics',
    icon: 'Activity',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['توثيق الأنشطة', 'الصور والفيديوهات', 'أهداف النشاط', 'نتائج التقييم'],
    tags: ['أنشطة', 'تقرير', 'توثيق'],
  },
  {
    title: 'تقرير البرامج التعليمية',
    slug: 'programs-report',
    description: 'تقرير شامل للبرامج التعليمية المنفذة مع تقييم الأثر.',
    short_description: 'توثيق وتقييم البرامج التعليمية',
    category: 'reports-analytics',
    icon: 'BookMarked',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['وصف البرنامج', 'الأهداف', 'آلية التنفيذ', 'تقييم الأثر', 'التوصيات'],
    tags: ['برامج', 'تقرير', 'تقييم'],
  },
  {
    title: 'تقرير المتفوقين والمتأخرين دراسياً',
    slug: 'students-classification-report',
    description: 'تقرير تصنيفي للطلاب المتفوقين والمتأخرين دراسياً مع خطط الرعاية.',
    short_description: 'تصنيف المتفوقين والمتأخرين دراسياً',
    category: 'reports-analytics',
    icon: 'Users',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['تصنيف الطلاب', 'خطط رعاية المتفوقين', 'خطط علاج المتأخرين', 'متابعة دورية'],
    tags: ['متفوقين', 'متأخرين', 'تصنيف'],
  },
  {
    title: 'تقرير نهاية العام الدراسي',
    slug: 'end-of-year-report',
    description: 'تقرير شامل لنهاية العام الدراسي يلخص جميع الإنجازات والتحديات والتوصيات.',
    short_description: 'تقرير شامل لنهاية العام الدراسي',
    category: 'reports-analytics',
    icon: 'FileCheck',
    price: 0,
    is_free: true,
    is_popular: true,
    is_new: false,
    status: 'active',
    features: ['ملخص الإنجازات', 'التحديات', 'الإحصائيات', 'التوصيات', 'خطة العام القادم'],
    tags: ['نهاية العام', 'تقرير سنوي', 'ملخص'],
  },

  // ========================================
  // 4. الخطط التعليمية (9 خدمات)
  // ========================================
  {
    title: 'الخطة العلاجية للطلاب المتأخرين دراسياً',
    slug: 'remedial-plan',
    description: 'خطة علاجية شاملة للطلاب المتأخرين دراسياً مناسبة لجميع المراحل والمواد الدراسية.',
    short_description: 'خطة علاجية شاملة لجميع المراحل',
    category: 'educational-plans',
    icon: 'HeartPulse',
    price: 0,
    is_free: true,
    is_popular: true,
    is_new: false,
    status: 'active',
    features: ['تشخيص نقاط الضعف', 'أهداف علاجية', 'أنشطة علاجية', 'أدوات التقويم', 'متابعة التحسن'],
    tags: ['خطة علاجية', 'متأخرين', 'علاج'],
  },
  {
    title: 'الخطة الإثرائية للطلاب المتفوقين',
    slug: 'enrichment-plan',
    description: 'خطة إثرائية للطلاب المتفوقين لتعزيز قدراتهم وتنمية مواهبهم.',
    short_description: 'خطة إثرائية للطلاب المتفوقين',
    category: 'educational-plans',
    icon: 'Sparkles',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['أنشطة إثرائية', 'مشاريع بحثية', 'مسابقات', 'تنمية المواهب', 'تحديات فكرية'],
    tags: ['خطة إثرائية', 'متفوقين', 'موهوبين'],
  },
  {
    title: 'خطة الفاقد التعليمي',
    slug: 'learning-loss-plan',
    description: 'خطة شاملة لمعالجة الفاقد التعليمي لجميع المواد الدراسية.',
    short_description: 'خطة معالجة الفاقد التعليمي',
    category: 'educational-plans',
    icon: 'Target',
    price: 0,
    is_free: true,
    is_popular: true,
    is_new: false,
    status: 'active',
    features: ['تحديد الفاقد', 'خطة المعالجة', 'الجدول الزمني', 'أدوات القياس', 'متابعة التقدم'],
    tags: ['فاقد تعليمي', 'خطة', 'معالجة'],
  },
  {
    title: 'خطة التطوير المهني للمعلم',
    slug: 'professional-development-plan',
    description: 'خطة تطوير مهني شاملة للمعلم تتضمن الأهداف والبرامج التدريبية.',
    short_description: 'خطة تطوير مهني للمعلم',
    category: 'educational-plans',
    icon: 'TrendingUp',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['تحليل الاحتياجات', 'الأهداف المهنية', 'البرامج التدريبية', 'الجدول الزمني', 'مؤشرات النجاح'],
    tags: ['تطوير مهني', 'تدريب', 'معلم'],
  },
  {
    title: 'خطة النشاط المدرسي',
    slug: 'school-activity-plan',
    description: 'خطة شاملة للأنشطة المدرسية خلال العام الدراسي.',
    short_description: 'خطة الأنشطة المدرسية السنوية',
    category: 'educational-plans',
    icon: 'Calendar',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['الأنشطة الصفية', 'الأنشطة اللاصفية', 'الفعاليات', 'المسابقات', 'الرحلات'],
    tags: ['نشاط', 'خطة', 'أنشطة مدرسية'],
  },
  {
    title: 'خطة التوجيه الطلابي',
    slug: 'student-guidance-plan',
    description: 'خطة شاملة لبرامج التوجيه والإرشاد الطلابي.',
    short_description: 'خطة التوجيه والإرشاد الطلابي',
    category: 'educational-plans',
    icon: 'Compass',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['البرامج الوقائية', 'البرامج العلاجية', 'البرامج الإنمائية', 'الجدول الزمني'],
    tags: ['توجيه', 'إرشاد', 'طلابي'],
  },
  {
    title: 'خطة الإرشاد الأكاديمي',
    slug: 'academic-counseling-plan',
    description: 'خطة إرشاد أكاديمي لمساعدة الطلاب في اختياراتهم الدراسية.',
    short_description: 'خطة الإرشاد الأكاديمي للطلاب',
    category: 'educational-plans',
    icon: 'GraduationCap',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['التوجيه المهني', 'اختيار التخصص', 'المسارات الدراسية', 'الاستشارات'],
    tags: ['إرشاد أكاديمي', 'توجيه', 'تخصص'],
  },
  {
    title: 'خطة الأمن والسلامة المدرسية',
    slug: 'school-safety-plan',
    description: 'خطة شاملة للأمن والسلامة في المدرسة.',
    short_description: 'خطة الأمن والسلامة المدرسية',
    category: 'educational-plans',
    icon: 'ShieldCheck',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['إجراءات السلامة', 'خطة الإخلاء', 'التدريبات', 'فحص المرافق', 'التقارير الدورية'],
    tags: ['أمن', 'سلامة', 'إخلاء'],
  },
  {
    title: 'خطة الإخلاء والطوارئ',
    slug: 'evacuation-plan',
    description: 'خطة إخلاء وطوارئ مفصلة للمدرسة.',
    short_description: 'خطة الإخلاء والطوارئ المدرسية',
    category: 'educational-plans',
    icon: 'Siren',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['مسارات الإخلاء', 'نقاط التجمع', 'فريق الطوارئ', 'التدريبات الدورية'],
    tags: ['إخلاء', 'طوارئ', 'سلامة'],
  },

  // ========================================
  // 5. الشهادات والتقدير (9 خدمات)
  // ========================================
  {
    title: 'شهادة شكر وتقدير للمعلم/ة',
    slug: 'teacher-appreciation-certificate',
    description: 'شهادة شكر وتقدير احترافية للمعلم والمعلمة بتصاميم متعددة.',
    short_description: 'شهادة شكر وتقدير للمعلم/ة',
    category: 'certificates-awards',
    icon: 'Award',
    price: 0,
    is_free: true,
    is_popular: true,
    is_new: false,
    status: 'active',
    features: ['تصاميم متعددة', 'تخصيص كامل', 'طباعة عالية الجودة', 'تصدير PDF'],
    tags: ['شهادة', 'شكر', 'تقدير', 'معلم'],
  },
  {
    title: 'شهادة شكر وتقدير للطالب/ة',
    slug: 'student-appreciation-certificate',
    description: 'شهادة شكر وتقدير للطالب والطالبة بتصاميم جذابة.',
    short_description: 'شهادة شكر وتقدير للطالب/ة',
    category: 'certificates-awards',
    icon: 'Star',
    price: 0,
    is_free: true,
    is_popular: true,
    is_new: false,
    status: 'active',
    features: ['تصاميم طلابية', 'ألوان جذابة', 'تخصيص كامل', 'تصدير PDF'],
    tags: ['شهادة', 'شكر', 'طالب', 'طالبة'],
  },
  {
    title: 'شهادة حضور دورة تدريبية',
    slug: 'training-attendance-certificate',
    description: 'شهادة حضور دورة تدريبية بتصميم احترافي.',
    short_description: 'شهادة حضور دورة تدريبية',
    category: 'certificates-awards',
    icon: 'BadgeCheck',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['اسم الدورة', 'عدد الساعات', 'تاريخ الحضور', 'المدرب', 'تصدير PDF'],
    tags: ['شهادة', 'حضور', 'دورة', 'تدريب'],
  },
  {
    title: 'شهادة مشاركة في ورشة عمل',
    slug: 'workshop-participation-certificate',
    description: 'شهادة مشاركة في ورشة عمل بتصميم احترافي.',
    short_description: 'شهادة مشاركة في ورشة عمل',
    category: 'certificates-awards',
    icon: 'Users',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['اسم الورشة', 'المحاور', 'التاريخ', 'المقدم', 'تصدير PDF'],
    tags: ['شهادة', 'مشاركة', 'ورشة عمل'],
  },
  {
    title: 'شهادة مشاركة في مبادرة',
    slug: 'initiative-participation-certificate',
    description: 'شهادة مشاركة في مبادرة تعليمية أو مجتمعية.',
    short_description: 'شهادة مشاركة في مبادرة',
    category: 'certificates-awards',
    icon: 'Lightbulb',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['اسم المبادرة', 'الدور', 'الفترة', 'الجهة المنظمة'],
    tags: ['شهادة', 'مبادرة', 'مشاركة'],
  },
  {
    title: 'شهادة تفوق دراسي',
    slug: 'academic-excellence-certificate',
    description: 'شهادة تفوق دراسي للطلاب المتميزين.',
    short_description: 'شهادة تفوق دراسي',
    category: 'certificates-awards',
    icon: 'Trophy',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['المعدل', 'الترتيب', 'المرحلة', 'الفصل الدراسي'],
    tags: ['شهادة', 'تفوق', 'تميز'],
  },
  {
    title: 'شهادة حسن سلوك',
    slug: 'good-behavior-certificate',
    description: 'شهادة حسن سلوك ومواظبة للطلاب.',
    short_description: 'شهادة حسن سلوك ومواظبة',
    category: 'certificates-awards',
    icon: 'ThumbsUp',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['السلوك', 'المواظبة', 'الفترة', 'ملاحظات'],
    tags: ['شهادة', 'سلوك', 'مواظبة'],
  },
  {
    title: 'شهادة إتمام برنامج',
    slug: 'program-completion-certificate',
    description: 'شهادة إتمام برنامج تعليمي أو تدريبي.',
    short_description: 'شهادة إتمام برنامج',
    category: 'certificates-awards',
    icon: 'CheckCircle',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['اسم البرنامج', 'المدة', 'المحتوى', 'الجهة'],
    tags: ['شهادة', 'إتمام', 'برنامج'],
  },
  {
    title: 'شهادة تطوع',
    slug: 'volunteer-certificate',
    description: 'شهادة تطوع ومشاركة مجتمعية.',
    short_description: 'شهادة تطوع ومشاركة مجتمعية',
    category: 'certificates-awards',
    icon: 'HandHeart',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: true,
    status: 'active',
    features: ['نوع التطوع', 'عدد الساعات', 'الجهة المستفيدة', 'الفترة'],
    tags: ['شهادة', 'تطوع', 'مجتمع'],
  },

  // ========================================
  // 6. السجلات المدرسية (13 خدمة)
  // ========================================
  {
    title: 'سجل الحضور والغياب اليومي',
    slug: 'daily-attendance-record',
    description: 'سجل يومي لمتابعة حضور وغياب الطلاب.',
    short_description: 'سجل الحضور والغياب اليومي',
    category: 'school-records',
    icon: 'CalendarCheck',
    price: 0,
    is_free: true,
    is_popular: true,
    is_new: false,
    status: 'active',
    features: ['تسجيل يومي', 'إحصائيات شهرية', 'تقارير الغياب', 'إشعارات أولياء الأمور'],
    tags: ['حضور', 'غياب', 'سجل يومي'],
  },
  {
    title: 'سجل الدرجات والتقييمات',
    slug: 'grades-record',
    description: 'سجل شامل لدرجات الطلاب وتقييماتهم.',
    short_description: 'سجل الدرجات والتقييمات',
    category: 'school-records',
    icon: 'FileSpreadsheet',
    price: 0,
    is_free: true,
    is_popular: true,
    is_new: false,
    status: 'active',
    features: ['رصد الدرجات', 'التقويم المستمر', 'الاختبارات', 'المشاركة', 'الواجبات'],
    tags: ['درجات', 'تقييم', 'سجل'],
  },
  {
    title: 'سجل المتابعة اليومية',
    slug: 'daily-follow-up-record',
    description: 'سجل متابعة يومية لأداء الطلاب في الحصص.',
    short_description: 'سجل المتابعة اليومية',
    category: 'school-records',
    icon: 'ClipboardList',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['متابعة يومية', 'ملاحظات المعلم', 'تقييم الأداء', 'الواجبات'],
    tags: ['متابعة', 'يومي', 'سجل'],
  },
  {
    title: 'سجل الملاحظات السلوكية',
    slug: 'behavioral-notes-record',
    description: 'سجل لتوثيق الملاحظات السلوكية للطلاب.',
    short_description: 'سجل الملاحظات السلوكية',
    category: 'school-records',
    icon: 'AlertCircle',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['توثيق الملاحظات', 'تصنيف السلوك', 'الإجراءات', 'المتابعة'],
    tags: ['سلوك', 'ملاحظات', 'سجل'],
  },
  {
    title: 'سجل التواصل مع أولياء الأمور',
    slug: 'parent-communication-record',
    description: 'سجل لتوثيق التواصل مع أولياء الأمور.',
    short_description: 'سجل التواصل مع أولياء الأمور',
    category: 'school-records',
    icon: 'Phone',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['تاريخ التواصل', 'نوع التواصل', 'الموضوع', 'النتيجة', 'المتابعة'],
    tags: ['أولياء أمور', 'تواصل', 'سجل'],
  },
  {
    title: 'سجل الزيارات الصفية',
    slug: 'classroom-visits-record',
    description: 'سجل لتوثيق الزيارات الصفية وملاحظات المشرف.',
    short_description: 'سجل الزيارات الصفية',
    category: 'school-records',
    icon: 'Eye',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['تاريخ الزيارة', 'المعلم', 'الملاحظات', 'التوصيات', 'المتابعة'],
    tags: ['زيارات صفية', 'إشراف', 'سجل'],
  },
  {
    title: 'سجل الاجتماعات المدرسية',
    slug: 'school-meetings-record',
    description: 'سجل لتوثيق محاضر الاجتماعات المدرسية.',
    short_description: 'سجل الاجتماعات المدرسية',
    category: 'school-records',
    icon: 'Users',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['محضر الاجتماع', 'الحضور', 'القرارات', 'التوصيات', 'المتابعة'],
    tags: ['اجتماعات', 'محاضر', 'سجل'],
  },
  {
    title: 'سجل العهد المدرسية',
    slug: 'school-assets-record',
    description: 'سجل لتوثيق العهد والأصول المدرسية.',
    short_description: 'سجل العهد المدرسية',
    category: 'school-records',
    icon: 'Package',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['قائمة العهد', 'المستلم', 'الحالة', 'تاريخ الاستلام', 'الإرجاع'],
    tags: ['عهد', 'أصول', 'سجل'],
  },
  {
    title: 'سجل الصادر والوارد',
    slug: 'correspondence-log',
    description: 'سجل لتوثيق المراسلات الصادرة والواردة.',
    short_description: 'سجل الصادر والوارد',
    category: 'school-records',
    icon: 'Mail',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['رقم الصادر/الوارد', 'التاريخ', 'الموضوع', 'الجهة', 'الإجراء'],
    tags: ['صادر', 'وارد', 'مراسلات'],
  },
  {
    title: 'سجل المعامل والمختبرات',
    slug: 'labs-record',
    description: 'سجل لتوثيق استخدام المعامل والمختبرات المدرسية.',
    short_description: 'سجل المعامل والمختبرات',
    category: 'school-records',
    icon: 'FlaskConical',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['جدول الاستخدام', 'المواد', 'التجارب', 'السلامة', 'الصيانة'],
    tags: ['معامل', 'مختبرات', 'سجل'],
  },
  {
    title: 'سجل المكتبة المدرسية',
    slug: 'library-record',
    description: 'سجل لإدارة المكتبة المدرسية والإعارة.',
    short_description: 'سجل المكتبة المدرسية',
    category: 'school-records',
    icon: 'Library',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['فهرس الكتب', 'سجل الإعارة', 'الإرجاع', 'الجرد', 'التقارير'],
    tags: ['مكتبة', 'إعارة', 'كتب'],
  },
  {
    title: 'سجل النشاط الطلابي',
    slug: 'student-activity-record',
    description: 'سجل لتوثيق مشاركات الطلاب في الأنشطة المدرسية.',
    short_description: 'سجل النشاط الطلابي',
    category: 'school-records',
    icon: 'Zap',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['الأنشطة', 'المشاركون', 'التقييم', 'الصور', 'التقارير'],
    tags: ['نشاط', 'طلابي', 'سجل'],
  },
  {
    title: 'سجل الإذاعة المدرسية',
    slug: 'school-broadcast-record',
    description: 'سجل لتوثيق برامج الإذاعة المدرسية.',
    short_description: 'سجل الإذاعة المدرسية',
    category: 'school-records',
    icon: 'Radio',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['البرنامج اليومي', 'المشاركون', 'المواضيع', 'التقييم'],
    tags: ['إذاعة', 'مدرسية', 'سجل'],
  },

  // ========================================
  // 7. ورش العمل والتدريب (6 خدمات)
  // ========================================
  {
    title: 'نموذج تقرير ورشة عمل',
    slug: 'workshop-report-template',
    description: 'نموذج احترافي لتوثيق ورش العمل المنفذة.',
    short_description: 'نموذج تقرير ورشة عمل',
    category: 'workshops-training',
    icon: 'FileText',
    price: 0,
    is_free: true,
    is_popular: true,
    is_new: false,
    status: 'active',
    features: ['عنوان الورشة', 'الأهداف', 'المحاور', 'المخرجات', 'التقييم', 'الصور'],
    tags: ['ورشة عمل', 'تقرير', 'نموذج'],
  },
  {
    title: 'نموذج خطة تدريبية',
    slug: 'training-plan-template',
    description: 'نموذج لإعداد خطة تدريبية شاملة.',
    short_description: 'نموذج خطة تدريبية',
    category: 'workshops-training',
    icon: 'ClipboardList',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['الأهداف التدريبية', 'المحتوى', 'الأنشطة', 'الجدول الزمني', 'التقييم'],
    tags: ['خطة تدريبية', 'تدريب', 'نموذج'],
  },
  {
    title: 'نموذج تقييم برنامج تدريبي',
    slug: 'training-evaluation-template',
    description: 'نموذج لتقييم البرامج التدريبية المنفذة.',
    short_description: 'نموذج تقييم برنامج تدريبي',
    category: 'workshops-training',
    icon: 'Star',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['معايير التقييم', 'استبيان المتدربين', 'تحليل النتائج', 'التوصيات'],
    tags: ['تقييم', 'تدريب', 'برنامج'],
  },
  {
    title: 'نموذج حقيبة تدريبية',
    slug: 'training-kit-template',
    description: 'نموذج لإعداد حقيبة تدريبية متكاملة.',
    short_description: 'نموذج حقيبة تدريبية',
    category: 'workshops-training',
    icon: 'Briefcase',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['دليل المدرب', 'دليل المتدرب', 'العروض التقديمية', 'أوراق العمل', 'التقييم'],
    tags: ['حقيبة تدريبية', 'تدريب', 'نموذج'],
  },
  {
    title: 'نموذج تقرير دورة تدريبية',
    slug: 'training-course-report',
    description: 'نموذج لتوثيق الدورات التدريبية المنفذة.',
    short_description: 'نموذج تقرير دورة تدريبية',
    category: 'workshops-training',
    icon: 'FileCheck',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['بيانات الدورة', 'المحتوى', 'المشاركون', 'النتائج', 'التوصيات'],
    tags: ['دورة', 'تدريب', 'تقرير'],
  },
  {
    title: 'نموذج استبيان تقييم التدريب',
    slug: 'training-survey-template',
    description: 'نموذج استبيان لتقييم رضا المتدربين.',
    short_description: 'استبيان تقييم التدريب',
    category: 'workshops-training',
    icon: 'MessageSquare',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['أسئلة التقييم', 'مقياس الرضا', 'الملاحظات', 'التحليل'],
    tags: ['استبيان', 'تقييم', 'تدريب'],
  },

  // ========================================
  // 8. المبادرات والمشاريع (6 خدمات)
  // ========================================
  {
    title: 'نموذج توثيق مبادرة تعليمية',
    slug: 'educational-initiative-template',
    description: 'نموذج شامل لتوثيق المبادرات التعليمية مع الأهداف والنتائج.',
    short_description: 'نموذج توثيق مبادرة تعليمية',
    category: 'initiatives-projects',
    icon: 'Lightbulb',
    price: 0,
    is_free: true,
    is_popular: true,
    is_new: false,
    status: 'active',
    features: ['اسم المبادرة', 'الأهداف', 'الفئة المستهدفة', 'آلية التنفيذ', 'النتائج', 'الأثر'],
    tags: ['مبادرة', 'توثيق', 'تعليمية'],
  },
  {
    title: 'نموذج خطة مشروع مدرسي',
    slug: 'school-project-plan',
    description: 'نموذج لإعداد خطة مشروع مدرسي متكامل.',
    short_description: 'نموذج خطة مشروع مدرسي',
    category: 'initiatives-projects',
    icon: 'Rocket',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['وصف المشروع', 'الأهداف', 'الميزانية', 'الجدول الزمني', 'فريق العمل', 'المخرجات'],
    tags: ['مشروع', 'خطة', 'مدرسي'],
  },
  {
    title: 'نموذج تقرير مبادرة',
    slug: 'initiative-report-template',
    description: 'نموذج لكتابة تقرير عن مبادرة منفذة.',
    short_description: 'نموذج تقرير مبادرة',
    category: 'initiatives-projects',
    icon: 'FileText',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['ملخص المبادرة', 'الإنجازات', 'التحديات', 'الدروس المستفادة', 'التوصيات'],
    tags: ['مبادرة', 'تقرير', 'توثيق'],
  },
  {
    title: 'نموذج توثيق ممارسة مهنية',
    slug: 'professional-practice-template',
    description: 'نموذج لتوثيق الممارسات المهنية المتميزة.',
    short_description: 'نموذج توثيق ممارسة مهنية',
    category: 'initiatives-projects',
    icon: 'Sparkles',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['وصف الممارسة', 'الأهداف', 'الأدلة والشواهد', 'الأثر', 'إمكانية التعميم'],
    tags: ['ممارسة مهنية', 'توثيق', 'تميز'],
  },
  {
    title: 'نموذج توثيق تجربة ناجحة',
    slug: 'success-story-template',
    description: 'نموذج لتوثيق التجارب الناجحة في المجال التعليمي.',
    short_description: 'نموذج توثيق تجربة ناجحة',
    category: 'initiatives-projects',
    icon: 'Trophy',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['وصف التجربة', 'السياق', 'الإجراءات', 'النتائج', 'الدروس المستفادة'],
    tags: ['تجربة ناجحة', 'توثيق', 'نجاح'],
  },
  {
    title: 'نموذج مشاركة مجتمعية',
    slug: 'community-participation-template',
    description: 'نموذج لتوثيق المشاركات المجتمعية والتطوعية.',
    short_description: 'نموذج مشاركة مجتمعية',
    category: 'initiatives-projects',
    icon: 'HandHeart',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['نوع المشاركة', 'الجهة المستفيدة', 'الأهداف', 'النتائج', 'الأثر المجتمعي'],
    tags: ['مشاركة مجتمعية', 'تطوع', 'مجتمع'],
  },

  // ========================================
  // 9. المجتمعات المهنية (6 خدمات)
  // ========================================
  {
    title: 'نموذج تقرير مجتمع تعلم مهني',
    slug: 'plc-report-template',
    description: 'نموذج لتوثيق أنشطة ونتائج مجتمع التعلم المهني.',
    short_description: 'تقرير مجتمع تعلم مهني',
    category: 'professional-communities',
    icon: 'Network',
    price: 0,
    is_free: true,
    is_popular: true,
    is_new: false,
    status: 'active',
    features: ['أهداف المجتمع', 'الأعضاء', 'الأنشطة المنفذة', 'النتائج', 'خطة التحسين'],
    tags: ['مجتمع مهني', 'تعلم', 'تقرير'],
  },
  {
    title: 'نموذج محضر اجتماع مجتمع مهني',
    slug: 'plc-meeting-minutes',
    description: 'نموذج لتوثيق محاضر اجتماعات مجتمع التعلم المهني.',
    short_description: 'محضر اجتماع مجتمع مهني',
    category: 'professional-communities',
    icon: 'ClipboardList',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['التاريخ والمكان', 'الحضور', 'جدول الأعمال', 'المناقشات', 'القرارات'],
    tags: ['محضر', 'اجتماع', 'مجتمع مهني'],
  },
  {
    title: 'نموذج خطة مجتمع تعلم مهني',
    slug: 'plc-plan-template',
    description: 'نموذج لإعداد خطة مجتمع تعلم مهني.',
    short_description: 'خطة مجتمع تعلم مهني',
    category: 'professional-communities',
    icon: 'Map',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['الرؤية والأهداف', 'الأعضاء', 'خطة العمل', 'الجدول الزمني', 'مؤشرات النجاح'],
    tags: ['خطة', 'مجتمع مهني', 'تعلم'],
  },
  {
    title: 'نموذج بحث الدرس (Lesson Study)',
    slug: 'lesson-study-template',
    description: 'نموذج لتوثيق بحث الدرس التعاوني بين المعلمين.',
    short_description: 'نموذج بحث الدرس التعاوني',
    category: 'professional-communities',
    icon: 'Search',
    price: 0,
    is_free: true,
    is_popular: true,
    is_new: false,
    status: 'active',
    features: ['هدف البحث', 'تخطيط الدرس', 'التنفيذ والملاحظة', 'التأمل والتحسين', 'النتائج'],
    tags: ['بحث الدرس', 'lesson study', 'تعاوني'],
  },
  {
    title: 'نموذج البحث الإجرائي',
    slug: 'action-research-template',
    description: 'نموذج لإعداد بحث إجرائي في المجال التعليمي.',
    short_description: 'نموذج البحث الإجرائي',
    category: 'professional-communities',
    icon: 'Microscope',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['مشكلة البحث', 'الأسئلة', 'المنهجية', 'جمع البيانات', 'التحليل', 'النتائج'],
    tags: ['بحث إجرائي', 'بحث', 'تعليمي'],
  },
  {
    title: 'نموذج تبادل الزيارات الصفية',
    slug: 'peer-observation-template',
    description: 'نموذج لتوثيق تبادل الزيارات الصفية بين المعلمين.',
    short_description: 'نموذج تبادل الزيارات الصفية',
    category: 'professional-communities',
    icon: 'ArrowLeftRight',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['المعلم الزائر', 'المعلم المُزار', 'الملاحظات', 'نقاط القوة', 'التوصيات'],
    tags: ['زيارات صفية', 'تبادل', 'ملاحظة'],
  },

  // ========================================
  // 10. التحضير والتخطيط (6 خدمات)
  // ========================================
  {
    title: 'نموذج تحضير درس يومي',
    slug: 'daily-lesson-plan',
    description: 'نموذج تحضير درس يومي شامل مع الأهداف والاستراتيجيات.',
    short_description: 'نموذج تحضير درس يومي',
    category: 'lesson-planning',
    icon: 'PenTool',
    price: 0,
    is_free: true,
    is_popular: true,
    is_new: false,
    status: 'active',
    features: ['الأهداف', 'المحتوى', 'الاستراتيجيات', 'الأنشطة', 'التقويم', 'الواجب'],
    tags: ['تحضير', 'درس', 'يومي'],
  },
  {
    title: 'نموذج تحضير وحدة دراسية',
    slug: 'unit-plan-template',
    description: 'نموذج لتحضير وحدة دراسية كاملة.',
    short_description: 'نموذج تحضير وحدة دراسية',
    category: 'lesson-planning',
    icon: 'BookOpen',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['أهداف الوحدة', 'الدروس', 'الأنشطة', 'التقويم', 'المصادر'],
    tags: ['تحضير', 'وحدة', 'دراسية'],
  },
  {
    title: 'نموذج توزيع المنهج الدراسي',
    slug: 'curriculum-distribution',
    description: 'نموذج لتوزيع المنهج الدراسي على أسابيع الفصل.',
    short_description: 'نموذج توزيع المنهج الدراسي',
    category: 'lesson-planning',
    icon: 'Calendar',
    price: 0,
    is_free: true,
    is_popular: true,
    is_new: false,
    status: 'active',
    features: ['الأسابيع', 'الوحدات', 'الدروس', 'الملاحظات', 'التعديلات'],
    tags: ['توزيع', 'منهج', 'أسابيع'],
  },
  {
    title: 'نموذج خطة أسبوعية',
    slug: 'weekly-plan-template',
    description: 'نموذج خطة أسبوعية للمعلم.',
    short_description: 'نموذج خطة أسبوعية',
    category: 'lesson-planning',
    icon: 'CalendarDays',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['أيام الأسبوع', 'الحصص', 'الأهداف', 'الأنشطة', 'الملاحظات'],
    tags: ['خطة', 'أسبوعية', 'جدول'],
  },
  {
    title: 'نموذج سجل الإنجاز اليومي',
    slug: 'daily-achievement-log',
    description: 'نموذج لتوثيق الإنجاز اليومي للمعلم.',
    short_description: 'سجل الإنجاز اليومي',
    category: 'lesson-planning',
    icon: 'CheckCircle',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['التاريخ', 'الحصة', 'الموضوع', 'ما تم إنجازه', 'الملاحظات'],
    tags: ['إنجاز', 'يومي', 'سجل'],
  },
  {
    title: 'نموذج تحليل المحتوى الدراسي',
    slug: 'content-analysis-template',
    description: 'نموذج لتحليل المحتوى الدراسي وتصنيف المهارات.',
    short_description: 'نموذج تحليل المحتوى الدراسي',
    category: 'lesson-planning',
    icon: 'Layers',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['المفاهيم', 'المهارات', 'القيم', 'مستويات التفكير', 'الأهداف'],
    tags: ['تحليل محتوى', 'مهارات', 'أهداف'],
  },

  // ========================================
  // 11. الاختبارات والتقويم (7 خدمات)
  // ========================================
  {
    title: 'نموذج اختبار فترة',
    slug: 'period-test-template',
    description: 'نموذج لإعداد اختبار فترة بتنسيق احترافي.',
    short_description: 'نموذج اختبار فترة',
    category: 'tests-assessment',
    icon: 'FileQuestion',
    price: 0,
    is_free: true,
    is_popular: true,
    is_new: false,
    status: 'active',
    features: ['رأس الاختبار', 'الأسئلة', 'الدرجات', 'التعليمات', 'نموذج الإجابة'],
    tags: ['اختبار', 'فترة', 'نموذج'],
  },
  {
    title: 'نموذج اختبار نهائي',
    slug: 'final-test-template',
    description: 'نموذج لإعداد اختبار نهائي بتنسيق رسمي.',
    short_description: 'نموذج اختبار نهائي',
    category: 'tests-assessment',
    icon: 'FileCheck',
    price: 0,
    is_free: true,
    is_popular: true,
    is_new: false,
    status: 'active',
    features: ['رأس الاختبار الرسمي', 'الأسئلة', 'جدول المواصفات', 'نموذج الإجابة'],
    tags: ['اختبار', 'نهائي', 'نموذج'],
  },
  {
    title: 'نموذج جدول مواصفات اختبار',
    slug: 'test-specifications-table',
    description: 'نموذج لإعداد جدول مواصفات الاختبار.',
    short_description: 'جدول مواصفات اختبار',
    category: 'tests-assessment',
    icon: 'Table',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['الموضوعات', 'مستويات الأهداف', 'عدد الأسئلة', 'الدرجات', 'النسب'],
    tags: ['جدول مواصفات', 'اختبار', 'تخطيط'],
  },
  {
    title: 'نموذج تحليل اختبار',
    slug: 'test-analysis-template',
    description: 'نموذج لتحليل نتائج الاختبار إحصائياً.',
    short_description: 'نموذج تحليل اختبار',
    category: 'tests-assessment',
    icon: 'BarChart',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['تحليل الأسئلة', 'معامل الصعوبة', 'معامل التمييز', 'الإحصائيات', 'التوصيات'],
    tags: ['تحليل', 'اختبار', 'إحصائيات'],
  },
  {
    title: 'نموذج رصد درجات',
    slug: 'grades-entry-template',
    description: 'نموذج لرصد درجات الطلاب بتنسيق منظم.',
    short_description: 'نموذج رصد درجات',
    category: 'tests-assessment',
    icon: 'Hash',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['قائمة الطلاب', 'الدرجات', 'المجموع', 'التقدير', 'الملاحظات'],
    tags: ['رصد', 'درجات', 'نموذج'],
  },
  {
    title: 'نموذج كشف متابعة التقويم المستمر',
    slug: 'continuous-assessment-sheet',
    description: 'نموذج لمتابعة التقويم المستمر للطلاب.',
    short_description: 'كشف متابعة التقويم المستمر',
    category: 'tests-assessment',
    icon: 'ClipboardCheck',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['المهارات', 'مستويات الإتقان', 'الملاحظات', 'التوصيات'],
    tags: ['تقويم مستمر', 'متابعة', 'مهارات'],
  },
  {
    title: 'نموذج تقرير أداء طالب',
    slug: 'student-performance-report',
    description: 'نموذج تقرير شامل عن أداء طالب فردي.',
    short_description: 'تقرير أداء طالب فردي',
    category: 'tests-assessment',
    icon: 'User',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['بيانات الطالب', 'الدرجات', 'السلوك', 'نقاط القوة', 'نقاط التحسين', 'التوصيات'],
    tags: ['تقرير', 'أداء', 'طالب'],
  },

  // ========================================
  // 12. الكشوفات والبيانات (7 خدمات)
  // ========================================
  {
    title: 'كشف بيانات الطلاب',
    slug: 'student-data-sheet',
    description: 'كشف شامل ببيانات الطلاب الأساسية.',
    short_description: 'كشف بيانات الطلاب',
    category: 'data-sheets',
    icon: 'Users',
    price: 0,
    is_free: true,
    is_popular: true,
    is_new: false,
    status: 'active',
    features: ['الاسم', 'رقم الهوية', 'تاريخ الميلاد', 'ولي الأمر', 'رقم التواصل', 'العنوان'],
    tags: ['كشف', 'بيانات', 'طلاب'],
  },
  {
    title: 'كشف درجات الطلاب',
    slug: 'student-grades-sheet',
    description: 'كشف درجات الطلاب لجميع المواد.',
    short_description: 'كشف درجات الطلاب',
    category: 'data-sheets',
    icon: 'FileSpreadsheet',
    price: 0,
    is_free: true,
    is_popular: true,
    is_new: false,
    status: 'active',
    features: ['المواد', 'الدرجات', 'المجموع', 'المعدل', 'التقدير'],
    tags: ['كشف', 'درجات', 'طلاب'],
  },
  {
    title: 'كشف الحضور والغياب',
    slug: 'attendance-sheet',
    description: 'كشف لمتابعة حضور وغياب الطلاب.',
    short_description: 'كشف الحضور والغياب',
    category: 'data-sheets',
    icon: 'CalendarCheck',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['الأيام', 'الحضور', 'الغياب', 'التأخر', 'الإجمالي'],
    tags: ['كشف', 'حضور', 'غياب'],
  },
  {
    title: 'كشف توزيع الطلاب على الفصول',
    slug: 'class-distribution-sheet',
    description: 'كشف توزيع الطلاب على الفصول الدراسية.',
    short_description: 'كشف توزيع الطلاب على الفصول',
    category: 'data-sheets',
    icon: 'LayoutGrid',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['الفصول', 'عدد الطلاب', 'الأسماء', 'الملاحظات'],
    tags: ['توزيع', 'فصول', 'طلاب'],
  },
  {
    title: 'كشف المعلمين والجداول',
    slug: 'teachers-schedule-sheet',
    description: 'كشف بيانات المعلمين وجداولهم الدراسية.',
    short_description: 'كشف المعلمين والجداول',
    category: 'data-sheets',
    icon: 'Clock',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['بيانات المعلم', 'المواد', 'الفصول', 'عدد الحصص', 'الجدول'],
    tags: ['معلمين', 'جداول', 'كشف'],
  },
  {
    title: 'كشف الحصص الاحتياطية',
    slug: 'substitute-classes-sheet',
    description: 'كشف لتنظيم الحصص الاحتياطية.',
    short_description: 'كشف الحصص الاحتياطية',
    category: 'data-sheets',
    icon: 'RefreshCw',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['المعلم الغائب', 'المعلم البديل', 'الحصة', 'الفصل', 'التاريخ'],
    tags: ['حصص احتياطية', 'بديل', 'كشف'],
  },
  {
    title: 'كشف المناوبات',
    slug: 'duty-roster-sheet',
    description: 'كشف لتنظيم مناوبات المعلمين.',
    short_description: 'كشف المناوبات',
    category: 'data-sheets',
    icon: 'Shield',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['المعلم', 'المكان', 'الوقت', 'اليوم', 'الملاحظات'],
    tags: ['مناوبات', 'إشراف', 'كشف'],
  },

  // ========================================
  // 13. الخطابات والمراسلات (8 خدمات)
  // ========================================
  {
    title: 'خطاب تعريف بالراتب',
    slug: 'salary-certificate-letter',
    description: 'نموذج خطاب تعريف بالراتب رسمي.',
    short_description: 'خطاب تعريف بالراتب',
    category: 'letters-correspondence',
    icon: 'FileText',
    price: 0,
    is_free: true,
    is_popular: true,
    is_new: false,
    status: 'active',
    features: ['بيانات الموظف', 'الراتب', 'البدلات', 'الجهة الموجه إليها'],
    tags: ['خطاب', 'تعريف', 'راتب'],
  },
  {
    title: 'خطاب مباشرة عمل',
    slug: 'work-commencement-letter',
    description: 'نموذج خطاب مباشرة عمل رسمي.',
    short_description: 'خطاب مباشرة عمل',
    category: 'letters-correspondence',
    icon: 'Briefcase',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['بيانات الموظف', 'تاريخ المباشرة', 'الوظيفة', 'المدرسة'],
    tags: ['خطاب', 'مباشرة', 'عمل'],
  },
  {
    title: 'خطاب إخلاء طرف',
    slug: 'clearance-letter',
    description: 'نموذج خطاب إخلاء طرف رسمي.',
    short_description: 'خطاب إخلاء طرف',
    category: 'letters-correspondence',
    icon: 'LogOut',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['بيانات الموظف', 'الجهات', 'التوقيعات', 'الملاحظات'],
    tags: ['خطاب', 'إخلاء طرف', 'نقل'],
  },
  {
    title: 'خطاب تكليف',
    slug: 'assignment-letter',
    description: 'نموذج خطاب تكليف بمهمة أو عمل إضافي.',
    short_description: 'خطاب تكليف',
    category: 'letters-correspondence',
    icon: 'UserPlus',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['المكلف', 'المهمة', 'المدة', 'الصلاحيات'],
    tags: ['خطاب', 'تكليف', 'مهمة'],
  },
  {
    title: 'خطاب شكر وتقدير رسمي',
    slug: 'official-appreciation-letter',
    description: 'نموذج خطاب شكر وتقدير رسمي من إدارة المدرسة.',
    short_description: 'خطاب شكر وتقدير رسمي',
    category: 'letters-correspondence',
    icon: 'Heart',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['المُقدَّر', 'سبب التقدير', 'التوقيع', 'الختم'],
    tags: ['خطاب', 'شكر', 'تقدير', 'رسمي'],
  },
  {
    title: 'خطاب دعوة لولي أمر',
    slug: 'parent-invitation-letter',
    description: 'نموذج خطاب دعوة لولي أمر لحضور اجتماع أو فعالية.',
    short_description: 'خطاب دعوة لولي أمر',
    category: 'letters-correspondence',
    icon: 'Mail',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['اسم ولي الأمر', 'اسم الطالب', 'سبب الدعوة', 'التاريخ والوقت'],
    tags: ['خطاب', 'دعوة', 'ولي أمر'],
  },
  {
    title: 'خطاب إحالة طالب',
    slug: 'student-referral-letter',
    description: 'نموذج خطاب إحالة طالب للتوجيه الطلابي أو جهة خارجية.',
    short_description: 'خطاب إحالة طالب',
    category: 'letters-correspondence',
    icon: 'ArrowRight',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['بيانات الطالب', 'سبب الإحالة', 'الجهة المُحال إليها', 'التوصيات'],
    tags: ['خطاب', 'إحالة', 'طالب'],
  },
  {
    title: 'خطاب طلب صيانة',
    slug: 'maintenance-request-letter',
    description: 'نموذج خطاب طلب صيانة للمرافق المدرسية.',
    short_description: 'خطاب طلب صيانة',
    category: 'letters-correspondence',
    icon: 'Wrench',
    price: 0,
    is_free: true,
    is_popular: false,
    is_new: false,
    status: 'active',
    features: ['المرفق', 'نوع العطل', 'الأولوية', 'الوصف التفصيلي'],
    tags: ['خطاب', 'صيانة', 'مرافق'],
  },
];

// ============================================
// دالة مساعدة لحساب الإحصائيات
// ============================================
export function getSeedStats() {
  const totalServices = SEED_SERVICES.length;
  const totalCategories = SEED_CATEGORIES.length;
  const freeServices = SEED_SERVICES.filter(s => s.is_free).length;
  const popularServices = SEED_SERVICES.filter(s => s.is_popular).length;
  
  const servicesByCategory: Record<string, number> = {};
  SEED_SERVICES.forEach(s => {
    servicesByCategory[s.category] = (servicesByCategory[s.category] || 0) + 1;
  });

  return {
    totalServices,
    totalCategories,
    freeServices,
    popularServices,
    servicesByCategory,
  };
}
