// src/lib/static-tools-seed.ts
/**
 * Default seed data for the educational tools.
 * AUTO-GENERATED from user-facing pages to ensure admin sees exactly what users see.
 * Used to initialize `static_tools` Firestore collection on first admin visit.
 */
import type { StaticTool, StaticForm, StaticFormField } from '@/types';

let _fieldSortOrder = 0;
function field(
    key: string,
    label_ar: string,
    type: StaticFormField['type'],
    opts: Partial<StaticFormField> = {}
): StaticFormField {
    return {
        id: `f_${key}_${++_fieldSortOrder}`,
        key,
        label_ar,
        type,
        sort_order: _fieldSortOrder,
        is_visible: true,
        ...opts,
    };
}

function form(
    id: string,
    title_ar: string,
    description_ar: string,
    fields: StaticFormField[],
    extra: Partial<StaticForm> = {}
): StaticForm {
    _fieldSortOrder = 0;                    // reset per form
    const rebuilt = fields.map((f, i) => ({ ...f, sort_order: i + 1 }));
    return {
        id,
        title_ar,
        description_ar,
        fields: rebuilt,
        is_active: true,
        sort_order: 1,
        ...extra,
    };
}

export type SeedToolDef = Omit<StaticTool, 'id'>;

export const DEFAULT_STATIC_TOOLS: SeedToolDef[] = [
    // ─── 1. نماذج وتقارير التوثيق ───────────────────────────────────────
    {
        title_ar: 'نماذج وتقارير التوثيق',
        title_en: 'Documentation Forms',
        description_ar: 'نماذج احترافية لتوثيق البرامج والأنشطة والتقارير بتصاميم جاهزة',
        icon: 'ClipboardList',
        gradient: 'from-blue-600 to-blue-700',
        href: '/documentation-forms',
        sort_order: 1,
        is_active: true,
        forms: [
            form('program-activity-advanced',
                'نموذج توثيق برنامج أو نشاط (المطور',
                'نموذج توثيق يقبل رفع شاهد واحد كحد أدنى وشاهدين كحد أقصى مع إمكانية وضع رابط للشواهد يتحول لباركود تلقائياً',
                [
                    field('education_dept',          'إدارة التعليم',                           'text', { required: true }),
                    field('school_name',             'اسم المدرسة',                             'text', { required: true }),
                    field('program_name',            'اسم البرنامج / المبادرة',                 'text', { required: true }),
                    field('location',                'مكان التنفيذ',                            'text'),
                    field('duration',                'مدة التنفيذ',                             'text'),
                    field('date',                    'تاريخ التنفيذ',                           'text'),
                    field('beneficiaries',           'المستفيدون / عددهم',                      'text'),
                    field('domain',                  'المجال',                                  'text'),
                    field('objectives',              'الأهداف',                                 'textarea', { rows: 5 }),
                    field('steps',                   'خطوات التنفيذ / الوصف',                   'textarea', { rows: 5 }),
                    field('right_signature_title',   'وظيفة التوقيع الأيمن',                    'text'),
                    field('right_signature_name',    'الاسم',                                   'text'),
                    field('left_signature_title',    'وظيفة التوقيع الأيسر',                    'text'),
                    field('left_signature_name',     'الاسم',                                   'text'),
                    field('image1',                  'صورة الشاهد الأول',                       'image', { required: true }),
                    field('evidence_url',            'ضع رابط الشواهد إن وجد لإنشاء باركود ووضعه بالنموذج', 'url'),
                ],
                { gradient: 'from-blue-500 to-blue-600', badge: 'الأكثر استخداماً', sort_order: 1 }
            ),
            form('strategy-brief',
                'نموذج تنفيذ استراتيجية مختصرة',
                'نموذج مختصر لتوثيق تنفيذ استراتيجية تعليمية',
                [
                    field('education_dept',          'إدارة التعليم/المنطقة/مكتب التعليم',      'textarea', { rows: 3 }),
                    field('school_name',             'اسم المدرسة',                             'text', { required: true }),
                    field('date',                    'تاريخ التنفيذ',                           'text'),
                    field('subject',                 'المادة',                                  'text'),
                    field('strategy',                'استراتيجية التعلم',                       'text', { required: true }),
                    field('students_count',          'عدد المستفيدين',                          'text'),
                    field('grade',                   'الفرحة الدراسية',                         'text'),
                    field('class',                   'الفصل',                                   'text'),
                    field('lesson',                  'اسم الدرس',                               'text'),
                    field('objectives',              'الأهداف',                                 'textarea', { rows: 5 }),
                    field('teacher_name',            'اسم المعلم',                              'textarea', { rows: 2 }),
                    field('other_name',              'اسم آخر',                                 'textarea', { rows: 2 }),
                    field('twitter',                 'حساب تويتر',                              'text'),
                    field('image1',                  'الشاهد الأول',                            'image'),
                    field('image2',                  'الشاهد الثاني',                           'image'),
                ],
                { gradient: 'from-emerald-500 to-green-600', sort_order: 2 }
            ),
            form('program-coverage',
                'تقرير تنفيذ برنامج (تغطية',
                'تقرير تغطية لتنفيذ برنامج مع شاهد واحد',
                [
                    field('education_dept',          'إدارة التعليم',                           'textarea', { rows: 3 }),
                    field('edu_office',              'مكتب التعليم',                            'text'),
                    field('program_name',            'اسم البرنامج',                            'text', { required: true }),
                    field('date',                    'تاريخ التنفيذ',                           'text'),
                    field('targets',                 'المستهدفون',                              'text'),
                    field('domain',                  'المجال',                                  'text'),
                    field('objectives',              'الأهداف',                                 'textarea', { rows: 5 }),
                    field('steps',                   'خطوات التنفيذ',                           'textarea', { rows: 5 }),
                    field('image1',                  'صورة الشاهد الأول',                       'image'),
                    field('image2',                  'صورة الشاهد الثاني',                      'image'),
                    field('image3',                  'صورة الشاهد الثالث',                      'image'),
                ],
                { gradient: 'from-violet-500 to-purple-600', sort_order: 3 }
            ),
            form('program-coverage-2',
                'تقرير تنفيذ برنامج (تغطية',
                'تقرير تغطية لتنفيذ برنامج مع شاهدين',
                [
                    field('edu_header',              'إدارة التعليم المنطقة مكتب التعليم',      'textarea', { rows: 3 }),
                    field('school_name',             'اسم المدرسة',                             'text', { required: true }),
                    field('program_name',            'اسم البرنامج',                            'text', { required: true }),
                    field('location',                'مكان التنفيذ',                            'text'),
                    field('targets',                 'المستهدفون',                              'text'),
                    field('targets_count',           'عدد المستهدفين',                          'text'),
                    field('date',                    'تاريخ التنفيذ',                           'text'),
                    field('objectives',              'الأهداف',                                 'textarea', { rows: 4 }),
                    field('image1',                  'صورة الشاهد الأول',                       'image'),
                    field('image2',                  'صورة الشاهد الثاني',                      'image'),
                ],
                { gradient: 'from-pink-500 to-rose-600', sort_order: 4 }
            ),
            form('program-coverage-4a',
                'تقرير تنفيذ برنامج (4 شواهد',
                'تقرير تغطية لتنفيذ برنامج مع 4 شواهد - التصميم الأول',
                [
                    field('edu_header',              'إدارة التعليم المنطقة مكتب التعليم',      'textarea', { rows: 3 }),
                    field('school_name',             'اسم المدرسة',                             'text', { required: true }),
                    field('program_name',            'اسم البرنامج',                            'text', { required: true }),
                    field('location',                'مكان التنفيذ',                            'text'),
                    field('targets',                 'المستهدفون',                              'text'),
                    field('targets_count',           'عدد المستهدفين',                          'text'),
                    field('date',                    'تاريخ التنفيذ',                           'text'),
                    field('objectives',              'الأهداف',                                 'textarea', { rows: 4 }),
                    field('image1',                  'صورة الشاهد الأول',                       'image'),
                    field('image2',                  'صورة الشاهد الثاني',                      'image'),
                    field('image3',                  'صورة الشاهد الثالث',                      'image'),
                    field('image4',                  'صورة الشاهد الرابع',                      'image'),
                ],
                { gradient: 'from-amber-500 to-orange-600', sort_order: 5 }
            ),
            form('program-coverage-4b',
                'تقرير تنفيذ برنامج (4 شواهد',
                'تقرير تغطية لتنفيذ برنامج مع 4 شواهد - التصميم الثاني',
                [
                    field('school_name',             'اسم المدرسة',                             'text', { required: true }),
                    field('program_name',            'اسم البرنامج',                            'text', { required: true }),
                    field('date',                    'التاريخ',                                 'text'),
                    field('description',             'وصف البرنامج',                            'textarea', { rows: 3 }),
                    field('image1',                  'الشاهد الأول',                            'image', { required: true }),
                    field('image2',                  'الشاهد الثاني',                           'image', { required: true }),
                    field('image3',                  'الشاهد الثالث',                           'image', { required: true }),
                    field('image4',                  'الشاهد الرابع',                           'image', { required: true }),
                ],
                { gradient: 'from-teal-500 to-cyan-600', sort_order: 6 }
            ),
            form('evidence-appendix',
                'ملحق شواهد (شواهد إضافية لأي تقرير',
                'إضافة شواهد إضافية لأي تقرير أو ملف',
                [
                    field('edu_header',              'إدارة التعليم المنطقة مكتب التعليم',      'textarea', { rows: 3 }),
                    field('title',                   'العنوان',                                 'text'),
                    field('twitter',                 'حساب تويتر',                              'text'),
                    field('image1',                  'صورة الشاهد الأول',                       'image'),
                    field('image2',                  'صورة الشاهد الثاني',                      'image'),
                    field('image3',                  'صورة الشاهد الثالث',                      'image'),
                    field('image4',                  'صورة الشاهد الرابع',                      'image'),
                    field('image5',                  'صورة الشاهد الخامس',                      'image'),
                    field('image6',                  'صورة الشاهد السادس',                      'image'),
                ],
                { gradient: 'from-indigo-500 to-blue-600', sort_order: 7 }
            ),
            form('report-cover',
                'غلاف لأي تقرير أو ملف',
                'إنشاء وتخصيص غلاف احترافي لأي تقرير أو ملف',
                [
                    field('title',                   'العنوان',                                 'textarea', { rows: 2 }),
                    field('school_name',             'اسم المدرسة',                             'textarea', { rows: 2 }),
                    field('author',                  'اسم معد الملف',                           'textarea', { rows: 2 }),
                    field('year',                    'التاريخ',                                 'text'),
                ],
                { gradient: 'from-slate-600 to-gray-700', sort_order: 8 }
            ),
            form('report-cover-landscape',
                'غلاف لأي تقرير أو ملف (أفقي',
                'غلاف بالعرض الأفقي لأي تقرير أو ملف',
                [
                    field('title',                   'العنوان',                                 'textarea', { rows: 2 }),
                    field('school_name',             'اسم المدرسة',                             'textarea', { rows: 2 }),
                    field('author',                  'اسم معد الملف',                           'textarea', { rows: 2 }),
                    field('year',                    'التاريخ',                                 'text'),
                ],
                { gradient: 'from-cyan-600 to-teal-700', sort_order: 9 }
            ),
            form('report-sub-cover',
                'غلاف فرعي داخلي لأي تقرير أو ملف',
                'غلاف فرعي داخلي للفصل بين أقسام التقرير',
                [
                    field('title',                   'العنوان',                                 'textarea', { rows: 2 }),
                    field('content',                 'المحتوى',                                 'textarea', { rows: 6 }),
                ],
                { gradient: 'from-rose-600 to-pink-700', sort_order: 10 }
            ),
            form('report-index',
                'فهرس تفاعلي لأي تقرير أو ملف',
                'إنشاء فهرس تفاعلي منظم لأي تقرير أو ملف',
                [
                    field('item1',                   'البند الأول',                             'text'),
                    field('page1',                   'رقم الصفحة',                              'text'),
                    field('item2',                   'البند الثاني',                            'text'),
                    field('page2',                   'رقم الصفحة',                              'text'),
                    field('item3',                   'البند الثالث',                            'text'),
                    field('page3',                   'رقم الصفحة',                              'text'),
                    field('item4',                   'البند الرابع',                            'text'),
                    field('page4',                   'رقم الصفحة',                              'text'),
                    field('item5',                   'البند الخامس',                            'text'),
                    field('page5',                   'رقم الصفحة',                              'text'),
                ],
                { gradient: 'from-green-600 to-emerald-700', sort_order: 11 }
            ),
            form('report-divider',
                'فواصل لأي تقرير أو ملف',
                'إنشاء فواصل جميلة للفصل بين أقسام التقرير',
                [
                    field('dividers',                'عنوان الفاصل. ضع كل عنوان في سطر، كل مرة تضغط إنتر سيتم إنشاء فاصل جديد:', 'textarea', { rows: 12 }),
                ],
                { gradient: 'from-purple-600 to-violet-700', sort_order: 12 }
            ),
            form('teacher-visit-exchange',
                'استمارة وتقرير تبادل الزيارات بين المعلمين',
                'نموذج لإنشاء استمارة وتقرير تبادل الزيارات بين المعلمين من جوالك مباشرة',
                [
                    field('edu_school',              'إدارة التعليم، اسم المدرسة',              'textarea', { rows: 3 }),
                    field('visiting_teachers',       'أسماء المعلمين الزائرين',                 'textarea', { rows: 3 }),
                    field('subject',                 'المادة',                                  'text'),
                    field('visit_date',              'اليوم والتاريخ',                          'text'),
                    field('class_grade',             'الصف / الفصل',                            'text'),
                    field('semester',                'الفصل الدراسي',                           'text'),
                    field('unit_lesson',             'الوحدة وعنوان الدرس',                     'textarea', { rows: 2 }),
                    field('visit_goals',             'أهداف الزيارة',                           'textarea', { rows: 5 }),
                ],
                { gradient: 'from-teal-600 to-emerald-700', sort_order: 13 }
            ),
            form('medical-physics-day',
                'تقرير اليوم العالمي للفيزياء الطبية',
                'نموذج تقرير جاهز لليوم العالمي للفيزياء الطبية (International Day of Medical Physics',
                [
                    field('edu_school',              'إدارة التعليم، اسم المدرسة',              'textarea', { rows: 3 }),
                    field('program_name',            'اسم البرنامج / المبادرة',                 'text'),
                    field('location',                'مكان التنفيذ',                            'text'),
                    field('duration',                'مدة التنفيذ',                             'text'),
                    field('date',                    'تاريخ التنفيذ',                           'text'),
                    field('beneficiaries',           'المستفيدون / عددهم',                      'text'),
                    field('domain',                  'المجال',                                  'text'),
                    field('objectives',              'الأهداف',                                 'textarea', { rows: 5 }),
                    field('steps',                   'خطوات التنفيذ / الوصف',                   'textarea', { rows: 5 }),
                    field('right_signature',         'وظيفة واسم التوقيع الأيمن',               'textarea', { rows: 2 }),
                    field('left_signature',          'وظيفة واسم التوقيع الأيسر',               'textarea', { rows: 2 }),
                    field('image1',                  'صورة الشاهد الأول',                       'image'),
                    field('image2',                  'صورة الشاهد الثاني',                      'image'),
                    field('evidence_url',            'ضع رابط الشواهد إن وجد لإنشاء باركود ووضعه بالنموذج', 'url'),
                ],
                { gradient: 'from-blue-700 to-indigo-800', sort_order: 14 }
            ),
        ],
    },

    // ─── 2. شواهد الأداء الجاهزة ────────────────────────────────────────
    {
        title_ar: 'شواهد الأداء الجاهزة',
        title_en: 'Performance Evidence Forms',
        description_ar: 'نماذج جاهزة لتوثيق شواهد الأداء الوظيفي المعتمدة — 11 بند',
        icon: 'ClipboardCheck',
        gradient: 'from-violet-600 to-purple-700',
        href: '/performance-evidence-forms',
        sort_order: 2,
        is_active: true,
        forms: [
            // ═══ بند 1: أداء الواجبات الوظيفية ═══
            form('school-broadcast', 'تقرير إذاعة مدرسية', 'توثيق تنفيذ إذاعة مدرسية',
                [
                    field('edu_school', 'إدارة التعليم، اسم المدرسة', 'textarea', { rows: 3 }),
                    field('program_name', 'اسم البرنامج / المبادرة', 'text', { required: true }),
                    field('implementors', 'المنفذ/ون', 'text'),
                    field('participants', 'المشاركـ/ون', 'text'),
                    field('location', 'مكان التنفيذ', 'text'),
                    field('duration', 'مدة التنفيذ', 'text'),
                    field('date', 'تاريخ التنفيذ', 'text'),
                    field('beneficiaries', 'المستفيدون / عددهم', 'text'),
                    field('domain', 'المجال', 'text'),
                    field('objectives', 'الأهداف', 'textarea', { rows: 5 }),
                    field('steps', 'خطوات التنفيذ / الوصف', 'textarea', { rows: 5 }),
                    field('right_signature', 'وظيفة واسم التوقيع الأيمن', 'textarea', { rows: 2 }),
                    field('left_signature', 'وظيفة واسم التوقيع الأيسر', 'textarea', { rows: 2 }),
                    field('image1', 'صورة الشاهد الأول', 'image', { required: true }),
                    field('image2', 'صورة الشاهد الثاني', 'image'),
                    field('evidence_url', 'رابط الشواهد (باركود)', 'url'),
                ],
                { gradient: 'from-blue-600 to-indigo-700', sort_order: 1, badge: 'job-duties' }
            ),
            form('extracurricular-activity', 'تقرير نشاط لا صفي', 'توثيق تنفيذ نشاط لا صفي',
                [
                    field('edu_school', 'إدارة التعليم، اسم المدرسة', 'textarea', { rows: 3 }),
                    field('program_name', 'اسم النشاط', 'text', { required: true }),
                    field('implementors', 'المنفذ/ون', 'text'),
                    field('participants', 'المشاركـ/ون', 'text'),
                    field('location', 'مكان التنفيذ', 'text'),
                    field('duration', 'مدة التنفيذ', 'text'),
                    field('date', 'تاريخ التنفيذ', 'text'),
                    field('beneficiaries', 'المستفيدون / عددهم', 'text'),
                    field('domain', 'المجال', 'text'),
                    field('objectives', 'الأهداف', 'textarea', { rows: 5 }),
                    field('steps', 'خطوات التنفيذ / الوصف', 'textarea', { rows: 5 }),
                    field('right_signature', 'التوقيع الأيمن', 'textarea', { rows: 2 }),
                    field('left_signature', 'التوقيع الأيسر', 'textarea', { rows: 2 }),
                    field('image1', 'صورة الشاهد الأول', 'image', { required: true }),
                    field('image2', 'صورة الشاهد الثاني', 'image'),
                ],
                { gradient: 'from-emerald-600 to-teal-700', sort_order: 2, badge: 'job-duties' }
            ),
            form('substitute-lesson', 'تقرير حصة انتظار', 'توثيق تنفيذ حصة انتظار',
                [
                    field('edu_school', 'إدارة التعليم، اسم المدرسة', 'textarea', { rows: 3 }),
                    field('teacher', 'اسم المعلم المنفذ', 'text', { required: true }),
                    field('absent_teacher', 'اسم المعلم الغائب', 'text'),
                    field('subject', 'المادة', 'text'),
                    field('grade', 'الصف', 'text'),
                    field('date', 'التاريخ', 'text'),
                    field('period', 'الحصة', 'text'),
                    field('students_count', 'عدد الطلاب', 'text'),
                    field('activities', 'الأنشطة المنفذة', 'textarea', { rows: 4 }),
                    field('notes', 'ملاحظات', 'textarea', { rows: 3 }),
                    field('right_signature', 'التوقيع الأيمن', 'textarea', { rows: 2 }),
                    field('left_signature', 'التوقيع الأيسر', 'textarea', { rows: 2 }),
                    field('image1', 'صورة الشاهد الأول', 'image'),
                    field('image2', 'صورة الشاهد الثاني', 'image'),
                ],
                { gradient: 'from-violet-600 to-purple-700', sort_order: 3, badge: 'job-duties' }
            ),
            // أيام عالمية ومناسبات
            form('saudi-science-day', 'تقرير يوم العلم السعودي', 'توثيق فعالية يوم العلم السعودي',
                [
                    field('edu_school', 'إدارة التعليم، اسم المدرسة', 'textarea', { rows: 3 }),
                    field('program_name', 'اسم البرنامج', 'text', { required: true }),
                    field('implementors', 'المنفذ/ون', 'text'),
                    field('date', 'تاريخ التنفيذ', 'text'),
                    field('beneficiaries', 'المستفيدون', 'text'),
                    field('objectives', 'الأهداف', 'textarea', { rows: 5 }),
                    field('steps', 'خطوات التنفيذ', 'textarea', { rows: 5 }),
                    field('right_signature', 'التوقيع الأيمن', 'textarea', { rows: 2 }),
                    field('left_signature', 'التوقيع الأيسر', 'textarea', { rows: 2 }),
                    field('image1', 'صورة الشاهد الأول', 'image', { required: true }),
                    field('image2', 'صورة الشاهد الثاني', 'image'),
                ],
                { gradient: 'from-blue-600 to-indigo-700', sort_order: 4, badge: 'job-duties' }
            ),
            form('gulf-talent-day', 'تقرير اليوم الخليجي للموهبة والإبداع', 'تقرير فعالية اليوم الخليجي للموهبة',
                [
                    field('edu_school', 'إدارة التعليم، اسم المدرسة', 'textarea', { rows: 3 }),
                    field('program_name', 'اسم البرنامج', 'text', { required: true }),
                    field('date', 'تاريخ التنفيذ', 'text'),
                    field('objectives', 'الأهداف', 'textarea', { rows: 5 }),
                    field('steps', 'خطوات التنفيذ', 'textarea', { rows: 5 }),
                    field('image1', 'صورة الشاهد الأول', 'image', { required: true }),
                    field('image2', 'صورة الشاهد الثاني', 'image'),
                ],
                { gradient: 'from-emerald-600 to-teal-700', sort_order: 5, badge: 'job-duties' }
            ),
            form('foundation-day', 'تقرير يوم التأسيس', 'تقرير فعالية يوم التأسيس السعودي',
                [
                    field('edu_school', 'إدارة التعليم، اسم المدرسة', 'textarea', { rows: 3 }),
                    field('program_name', 'اسم البرنامج', 'text', { required: true }),
                    field('date', 'تاريخ التنفيذ', 'text'),
                    field('objectives', 'الأهداف', 'textarea', { rows: 5 }),
                    field('steps', 'خطوات التنفيذ', 'textarea', { rows: 5 }),
                    field('image1', 'صورة الشاهد', 'image', { required: true }),
                    field('image2', 'صورة الشاهد الثاني', 'image'),
                ],
                { gradient: 'from-green-700 to-emerald-800', sort_order: 6, badge: 'job-duties' }
            ),
            form('education-day', 'تقرير اليوم العالمي للتعليم', 'تقرير فعالية اليوم العالمي للتعليم',
                [
                    field('edu_school', 'إدارة التعليم، اسم المدرسة', 'textarea', { rows: 3 }),
                    field('program_name', 'اسم البرنامج', 'text', { required: true }),
                    field('date', 'تاريخ التنفيذ', 'text'),
                    field('objectives', 'الأهداف', 'textarea', { rows: 5 }),
                    field('steps', 'خطوات التنفيذ', 'textarea', { rows: 5 }),
                    field('image1', 'صورة الشاهد', 'image', { required: true }),
                    field('image2', 'صورة الشاهد الثاني', 'image'),
                ],
                { gradient: 'from-amber-600 to-orange-600', sort_order: 7, badge: 'job-duties' }
            ),
            form('arabic-language-day', 'تقرير اليوم العالمي للغة العربية', 'تقرير فعالية اليوم العالمي للغة العربية',
                [
                    field('edu_school', 'إدارة التعليم، اسم المدرسة', 'textarea', { rows: 3 }),
                    field('program_name', 'اسم البرنامج', 'text', { required: true }),
                    field('date', 'تاريخ التنفيذ', 'text'),
                    field('objectives', 'الأهداف', 'textarea', { rows: 5 }),
                    field('steps', 'خطوات التنفيذ', 'textarea', { rows: 5 }),
                    field('image1', 'صورة الشاهد', 'image', { required: true }),
                    field('image2', 'صورة الشاهد الثاني', 'image'),
                ],
                { gradient: 'from-rose-600 to-pink-700', sort_order: 8, badge: 'job-duties' }
            ),
            form('child-day', 'تقرير اليوم العالمي للطفل', 'تقرير فعالية اليوم العالمي للطفل',
                [
                    field('edu_school', 'إدارة التعليم، اسم المدرسة', 'textarea', { rows: 3 }),
                    field('program_name', 'اسم البرنامج', 'text', { required: true }),
                    field('date', 'تاريخ التنفيذ', 'text'),
                    field('objectives', 'الأهداف', 'textarea', { rows: 5 }),
                    field('steps', 'خطوات التنفيذ', 'textarea', { rows: 5 }),
                    field('image1', 'صورة الشاهد', 'image', { required: true }),
                    field('image2', 'صورة الشاهد الثاني', 'image'),
                ],
                { gradient: 'from-cyan-600 to-blue-700', sort_order: 9, badge: 'job-duties' }
            ),
            form('tolerance-day', 'اليوم العالمي للتسامح', 'تقرير فعالية اليوم العالمي للتسامح',
                [
                    field('edu_school', 'إدارة التعليم، اسم المدرسة', 'textarea', { rows: 3 }),
                    field('program_name', 'اسم البرنامج', 'text', { required: true }),
                    field('date', 'تاريخ التنفيذ', 'text'),
                    field('objectives', 'الأهداف', 'textarea', { rows: 5 }),
                    field('steps', 'خطوات التنفيذ', 'textarea', { rows: 5 }),
                    field('image1', 'صورة الشاهد', 'image', { required: true }),
                    field('image2', 'صورة الشاهد الثاني', 'image'),
                ],
                { gradient: 'from-purple-600 to-violet-700', sort_order: 10, badge: 'job-duties' }
            ),
            form('diabetes-day', 'اليوم العالمي للسكري', 'تقرير فعالية اليوم العالمي للسكري',
                [
                    field('edu_school', 'إدارة التعليم، اسم المدرسة', 'textarea', { rows: 3 }),
                    field('program_name', 'اسم البرنامج', 'text', { required: true }),
                    field('date', 'تاريخ التنفيذ', 'text'),
                    field('objectives', 'الأهداف', 'textarea', { rows: 5 }),
                    field('steps', 'خطوات التنفيذ', 'textarea', { rows: 5 }),
                    field('image1', 'صورة الشاهد', 'image', { required: true }),
                    field('image2', 'صورة الشاهد الثاني', 'image'),
                ],
                { gradient: 'from-sky-600 to-blue-700', sort_order: 11, badge: 'job-duties' }
            ),
            form('disability-day', 'اليوم العالمي لذوي الإعاقة', 'تقرير فعالية اليوم العالمي لذوي الإعاقة',
                [
                    field('edu_school', 'إدارة التعليم، اسم المدرسة', 'textarea', { rows: 3 }),
                    field('program_name', 'اسم البرنامج', 'text', { required: true }),
                    field('date', 'تاريخ التنفيذ', 'text'),
                    field('objectives', 'الأهداف', 'textarea', { rows: 5 }),
                    field('steps', 'خطوات التنفيذ', 'textarea', { rows: 5 }),
                    field('image1', 'صورة الشاهد', 'image', { required: true }),
                    field('image2', 'صورة الشاهد الثاني', 'image'),
                ],
                { gradient: 'from-teal-600 to-cyan-700', sort_order: 12, badge: 'job-duties' }
            ),
            // ═══ بند 2: المجتمع المهني ═══
            form('plc-meeting-report', 'تقرير اجتماع مجتمع التعلم المهني', 'توثيق اجتماعات مجتمعات التعلم',
                [
                    field('school', 'اسم المدرسة', 'text', { required: true }),
                    field('teacher', 'اسم المعلم', 'text', { required: true }),
                    field('meeting_date', 'تاريخ الاجتماع', 'text'),
                    field('meeting_number', 'رقم الاجتماع', 'text'),
                    field('attendees', 'الحاضرون', 'textarea', { rows: 3 }),
                    field('agenda', 'محاور الاجتماع', 'textarea', { rows: 4 }),
                    field('decisions', 'القرارات والتوصيات', 'textarea', { rows: 3 }),
                    field('image1', 'صورة الشاهد', 'image', { required: true }),
                ],
                { gradient: 'from-indigo-600 to-blue-700', sort_order: 13, badge: 'professional-community' }
            ),
            form('peer-visit-report', 'تقرير تبادل الزيارات الصفية', 'توثيق تبادل الزيارات بين المعلمين',
                [
                    field('school', 'اسم المدرسة', 'text', { required: true }),
                    field('visitor', 'المعلم الزائر', 'text', { required: true }),
                    field('visited', 'المعلم المُزار', 'text', { required: true }),
                    field('date', 'تاريخ الزيارة', 'text'),
                    field('subject', 'المادة', 'text'),
                    field('strengths', 'نقاط القوة', 'textarea', { rows: 3 }),
                    field('improvements', 'نقاط التحسين', 'textarea', { rows: 3 }),
                    field('image1', 'صورة الشاهد', 'image', { required: true }),
                ],
                { gradient: 'from-indigo-600 to-blue-700', sort_order: 14, badge: 'professional-community' }
            ),
            // ═══ بند 3: أولياء الأمور ═══
            form('parents-comm-report', 'تقرير التواصل مع أولياء الأمور', 'توثيق التواصل مع أولياء الأمور',
                [
                    field('school', 'اسم المدرسة', 'text', { required: true }),
                    field('teacher', 'اسم المعلم', 'text', { required: true }),
                    field('grade', 'الصف', 'text'),
                    field('period', 'الفترة الزمنية', 'text'),
                    field('communication_type', 'نوع التواصل', 'text'),
                    field('parents_count', 'عدد أولياء الأمور', 'text'),
                    field('topics', 'موضوعات التواصل', 'textarea', { rows: 3 }),
                    field('image1', 'صورة الشاهد', 'image', { required: true }),
                ],
                { gradient: 'from-teal-600 to-emerald-600', sort_order: 15, badge: 'parents-interaction' }
            ),
            form('first-meeting-report', 'تقرير الاجتماع الأول لأولياء الأمور', 'تقرير الاجتماع الأول مع أولياء الأمور',
                [
                    field('school', 'اسم المدرسة', 'text', { required: true }),
                    field('teacher', 'اسم المعلم', 'text', { required: true }),
                    field('grade', 'الصف', 'text'),
                    field('date', 'تاريخ الاجتماع', 'text'),
                    field('attendees_count', 'عدد الحاضرين', 'text'),
                    field('agenda', 'محاور الاجتماع', 'textarea', { rows: 4 }),
                    field('decisions', 'القرارات والتوصيات', 'textarea', { rows: 3 }),
                    field('image1', 'صورة الشاهد الأول', 'image', { required: true }),
                    field('image2', 'صورة الشاهد الثاني', 'image'),
                ],
                { gradient: 'from-teal-600 to-emerald-600', sort_order: 16, badge: 'parents-interaction' }
            ),
            // ═══ بند 4: استراتيجيات التدريس ═══
            form('strategy-teacher', 'استراتيجية الطالب المعلم', 'تقرير تنفيذ استراتيجية الطالب المعلم',
                [
                    field('edu_school', 'إدارة التعليم، اسم المدرسة', 'textarea', { rows: 3 }),
                    field('teacher', 'اسم المعلم', 'text', { required: true }),
                    field('subject', 'المادة', 'text'), field('grade', 'الصف', 'text'),
                    field('date', 'التاريخ', 'text'), field('lesson', 'عنوان الدرس', 'text'),
                    field('description', 'وصف تطبيق الاستراتيجية', 'textarea', { rows: 4 }),
                    field('results', 'النتائج', 'textarea', { rows: 3 }),
                    field('image1', 'صورة الشاهد', 'image', { required: true }),
                ],
                { gradient: 'from-blue-600 to-indigo-700', sort_order: 17, badge: 'strategies' }
            ),
            form('strategy-think-pair', 'استراتيجية فكر-زاوج-شارك', 'تقرير تنفيذ استراتيجية فكر زاوج شارك',
                [
                    field('edu_school', 'إدارة التعليم، اسم المدرسة', 'textarea', { rows: 3 }),
                    field('teacher', 'اسم المعلم', 'text', { required: true }),
                    field('subject', 'المادة', 'text'), field('grade', 'الصف', 'text'),
                    field('date', 'التاريخ', 'text'),
                    field('description', 'وصف التطبيق', 'textarea', { rows: 4 }),
                    field('results', 'النتائج', 'textarea', { rows: 3 }),
                    field('image1', 'صورة الشاهد', 'image', { required: true }),
                ],
                { gradient: 'from-green-600 to-emerald-700', sort_order: 18, badge: 'strategies' }
            ),
            form('strategy-cooperative', 'استراتيجية التعليم التعاوني', 'تقرير تنفيذ التعليم التعاوني',
                [
                    field('edu_school', 'إدارة التعليم، اسم المدرسة', 'textarea', { rows: 3 }),
                    field('teacher', 'اسم المعلم', 'text', { required: true }),
                    field('subject', 'المادة', 'text'), field('grade', 'الصف', 'text'),
                    field('date', 'التاريخ', 'text'),
                    field('description', 'وصف التطبيق', 'textarea', { rows: 4 }),
                    field('results', 'النتائج', 'textarea', { rows: 3 }),
                    field('image1', 'صورة الشاهد', 'image', { required: true }),
                ],
                { gradient: 'from-amber-600 to-orange-600', sort_order: 19, badge: 'strategies' }
            ),
            form('strategy-flipped', 'استراتيجية الفصل المقلوب', 'تقرير تنفيذ الفصل المقلوب',
                [
                    field('edu_school', 'إدارة التعليم، اسم المدرسة', 'textarea', { rows: 3 }),
                    field('teacher', 'اسم المعلم', 'text', { required: true }),
                    field('subject', 'المادة', 'text'), field('grade', 'الصف', 'text'),
                    field('date', 'التاريخ', 'text'),
                    field('description', 'وصف التطبيق', 'textarea', { rows: 4 }),
                    field('results', 'النتائج', 'textarea', { rows: 3 }),
                    field('image1', 'صورة الشاهد', 'image', { required: true }),
                ],
                { gradient: 'from-indigo-600 to-violet-700', sort_order: 20, badge: 'strategies' }
            ),
            form('strategy-hot-seat', 'استراتيجية الكرسي الساخن', 'تقرير تنفيذ الكرسي الساخن',
                [
                    field('edu_school', 'إدارة التعليم، اسم المدرسة', 'textarea', { rows: 3 }),
                    field('teacher', 'اسم المعلم', 'text', { required: true }),
                    field('subject', 'المادة', 'text'), field('grade', 'الصف', 'text'),
                    field('date', 'التاريخ', 'text'),
                    field('description', 'وصف التطبيق', 'textarea', { rows: 4 }),
                    field('results', 'النتائج', 'textarea', { rows: 3 }),
                    field('image1', 'صورة الشاهد', 'image', { required: true }),
                ],
                { gradient: 'from-red-600 to-rose-700', sort_order: 21, badge: 'strategies' }
            ),
            form('strategy-gamification', 'استراتيجية التعلم باللعب', 'تقرير تنفيذ التعلم باللعب',
                [
                    field('edu_school', 'إدارة التعليم، اسم المدرسة', 'textarea', { rows: 3 }),
                    field('teacher', 'اسم المعلم', 'text', { required: true }),
                    field('subject', 'المادة', 'text'),
                    field('date', 'التاريخ', 'text'),
                    field('description', 'وصف التطبيق', 'textarea', { rows: 4 }),
                    field('results', 'النتائج', 'textarea', { rows: 3 }),
                    field('image1', 'صورة الشاهد', 'image', { required: true }),
                ],
                { gradient: 'from-orange-600 to-amber-700', sort_order: 22, badge: 'strategies' }
            ),
            // ═══ بند 7: التقنيات ═══
            form('teams-madrasati', 'تقرير درس عن بُعد (مدرستي وتيمز)', 'تقرير تفعيل درس عن بعد',
                [
                    field('edu_school', 'إدارة التعليم، اسم المدرسة', 'textarea', { rows: 3 }),
                    field('teacher', 'اسم المعلم', 'text', { required: true }),
                    field('subject', 'المادة', 'text'), field('grade', 'الصف', 'text'),
                    field('date', 'التاريخ', 'text'), field('lesson', 'عنوان الدرس', 'text'),
                    field('tools_used', 'الأدوات المستخدمة', 'textarea', { rows: 3 }),
                    field('description', 'وصف النشاط', 'textarea', { rows: 4 }),
                    field('image1', 'صورة الشاهد', 'image', { required: true }),
                ],
                { gradient: 'from-blue-600 to-indigo-700', sort_order: 23, badge: 'technical' }
            ),
            form('canva', 'تقرير استخدام Canva', 'تقرير استخدام أداة Canva',
                [
                    field('edu_school', 'إدارة التعليم، اسم المدرسة', 'textarea', { rows: 3 }),
                    field('teacher', 'اسم المعلم', 'text', { required: true }),
                    field('subject', 'المادة', 'text'), field('date', 'التاريخ', 'text'),
                    field('description', 'وصف الاستخدام', 'textarea', { rows: 4 }),
                    field('impact', 'الأثر على التعلم', 'textarea', { rows: 3 }),
                    field('image1', 'صورة الشاهد', 'image', { required: true }),
                ],
                { gradient: 'from-purple-500 to-pink-600', sort_order: 24, badge: 'technical' }
            ),
            form('kahoot', 'تقرير استخدام Kahoot!', 'تقرير استخدام Kahoot',
                [
                    field('edu_school', 'إدارة التعليم، اسم المدرسة', 'textarea', { rows: 3 }),
                    field('teacher', 'اسم المعلم', 'text', { required: true }),
                    field('subject', 'المادة', 'text'), field('date', 'التاريخ', 'text'),
                    field('description', 'وصف الاستخدام', 'textarea', { rows: 4 }),
                    field('impact', 'الأثر', 'textarea', { rows: 3 }),
                    field('image1', 'صورة الشاهد', 'image', { required: true }),
                ],
                { gradient: 'from-violet-700 to-purple-800', sort_order: 25, badge: 'technical' }
            ),
            // ═══ بند 8: البيئة التعليمية ═══
            form('env-assessment-report', 'تقرير تقييم البيئة المدرسية', 'توثيق حالة البيئة التعليمية',
                [
                    field('school', 'اسم المدرسة', 'text', { required: true }),
                    field('teacher', 'اسم المعلم', 'text', { required: true }),
                    field('date', 'التاريخ', 'text'),
                    field('env_type', 'نوع التهيئة', 'text'),
                    field('description', 'وصف التهيئة', 'textarea', { rows: 4 }),
                    field('impact', 'الأثر على المتعلمين', 'textarea', { rows: 3 }),
                    field('image1', 'صورة الشاهد الأول', 'image', { required: true }),
                    field('image2', 'صورة الشاهد الثاني', 'image'),
                ],
                { gradient: 'from-lime-600 to-green-700', sort_order: 26, badge: 'school-environment' }
            ),
            // ═══ بند 9: الإدارة الصفية ═══
            form('cm-positive-reinforcement', 'استراتيجية التعزيز الإيجابي', 'تقرير تطبيق التعزيز الإيجابي',
                [
                    field('edu_school', 'إدارة التعليم، اسم المدرسة', 'textarea', { rows: 3 }),
                    field('teacher', 'اسم المعلم', 'text', { required: true }),
                    field('grade', 'الصف', 'text'), field('date', 'التاريخ', 'text'),
                    field('description', 'وصف تطبيق الاستراتيجية', 'textarea', { rows: 4 }),
                    field('results', 'النتائج', 'textarea', { rows: 3 }),
                    field('image1', 'صورة الشاهد', 'image', { required: true }),
                ],
                { gradient: 'from-amber-600 to-orange-600', sort_order: 27, badge: 'classroom-management' }
            ),
            form('cm-rules', 'استراتيجية بناء القواعد الصفية', 'تقرير بناء القواعد مع الطلاب',
                [
                    field('edu_school', 'إدارة التعليم، اسم المدرسة', 'textarea', { rows: 3 }),
                    field('teacher', 'اسم المعلم', 'text', { required: true }),
                    field('grade', 'الصف', 'text'), field('date', 'التاريخ', 'text'),
                    field('description', 'وصف التطبيق', 'textarea', { rows: 4 }),
                    field('results', 'النتائج', 'textarea', { rows: 3 }),
                    field('image1', 'صورة الشاهد', 'image', { required: true }),
                ],
                { gradient: 'from-violet-600 to-purple-700', sort_order: 28, badge: 'classroom-management' }
            ),
            // ═══ بند 11: أساليب التقويم ═══
            form('formative-assessment', 'تقرير التقويم التكويني', 'توثيق أسلوب التقويم التكويني',
                [
                    field('school', 'اسم المدرسة', 'text', { required: true }),
                    field('teacher', 'اسم المعلم', 'text', { required: true }),
                    field('subject', 'المادة', 'text'), field('grade', 'الصف', 'text'),
                    field('assessment_type', 'نوع التقويم', 'text'),
                    field('description', 'وصف النشاط التقويمي', 'textarea', { rows: 4 }),
                    field('results', 'النتائج', 'textarea', { rows: 3 }),
                    field('recommendations', 'التوصيات', 'textarea', { rows: 3 }),
                    field('image1', 'صورة الشاهد', 'image', { required: true }),
                ],
                { gradient: 'from-purple-600 to-violet-700', sort_order: 29, badge: 'assessment-methods' }
            ),
            form('peer-assessment', 'تقرير تقويم الأقران', 'توثيق نشاط تقويم الأقران',
                [
                    field('school', 'اسم المدرسة', 'text', { required: true }),
                    field('teacher', 'اسم المعلم', 'text', { required: true }),
                    field('subject', 'المادة', 'text'), field('grade', 'الصف', 'text'),
                    field('description', 'وصف نشاط تقويم الأقران', 'textarea', { rows: 4 }),
                    field('results', 'النتائج والملاحظات', 'textarea', { rows: 3 }),
                    field('image1', 'صورة الشاهد', 'image', { required: true }),
                ],
                { gradient: 'from-purple-600 to-violet-700', sort_order: 30, badge: 'assessment-methods' }
            ),
        ],
    },

    // ─── 3. عناصر تقييم المعلمين ────────────────────────────────────────
    {
        title_ar: 'عناصر تقييم المعلمين',
        title_en: 'Teacher Evaluation Forms',
        description_ar: 'نماذج عناصر تقييم المعلمين ومؤشرات الأداء المهني',
        icon: 'GraduationCap',
        gradient: 'from-emerald-600 to-green-700',
        href: '/teacher-evaluation-forms',
        sort_order: 3,
        is_active: true,
        forms: [

            form('teacher-eval-main',
                'نموذج تقييم المعلم',
                'نموذج تقييم أداء المعلم وفق المعايير المهنية',
                [
                    field('school_name',       'اسم المدرسة',        'text',     { required: true }),
                    field('teacher_name',      'اسم المعلم/ة',       'text',     { required: true }),
                    field('subject',           'المادة',             'text' ),
                    field('grade',             'المرحلة الدراسية',   'text' ),
                    field('semester',          'الفصل الدراسي',      'text' ),
                    field('academic_year',     'العام الدراسي',      'text' ),
                    field('evaluation_date',   'تاريخ التقييم',      'text' ),
                    field('performance_notes', 'ملاحظات الأداء',     'textarea', { rows: 4 }),
                    field('strengths',         'نقاط القوة',         'textarea', { rows: 3 }),
                    field('improvements',      'مجالات التحسين',     'textarea', { rows: 3 }),
                    field('evaluator_name',    'اسم المقيّم',        'text' ),
                    field('principal_name',    'مدير المدرسة',       'text' ),
                ],
                { gradient: 'from-emerald-500 to-green-600' }
            ),
        
        ],
    },

    // ─── 4. تحليل النتائج ───────────────────────────────────────────────
    {
        title_ar: 'تحليل النتائج',
        title_en: 'Results Analysis',
        description_ar: 'تحليل نتائج الاختبارات واستخراج التقارير والإحصائيات التفصيلية مع رسوم بيانية تفاعلية',
        icon: 'BarChart3',
        gradient: 'from-blue-500 to-indigo-600',
        href: '/analyze-results',
        sort_order: 4,
        is_active: true,
        forms: [
            form('skills-analysis',
                'تقرير تحليل نتائج المهارات (ابتدائي',
                'تقرير تحليل نتائج مهارات الطلاب في المرحلة الابتدائية مع رسوم بيانية',
                [
                    field('edu_school',              'إدارة التعليم، اسم المدرسة',              'textarea', { rows: 3 }),
                    field('academic_year',           'العام الدراسي',                           'text'),
                    field('semester',                'الفصل الدراسي',                           'text'),
                    field('subject',                 'المادة',                                  'text', { required: true }),
                    field('grade',                   'الصف',                                    'text', { required: true }),
                    field('teacher',                 'اسم المعلم',                              'text', { required: true }),
                    field('students_count',          'عدد الطلاب',                              'text'),
                    field('exam_type',               'نوع الاختبار',                            'text'),
                    field('skills',                  'المهارات المقيّمة والنتائج',              'textarea', { rows: 6 }),
                    field('analysis',                'تحليل النتائج',                           'textarea', { rows: 4 }),
                    field('recommendations',         'التوصيات والخطة العلاجية',                'textarea', { rows: 4 }),
                    field('right_sig',               'وظيفة واسم التوقيع الأيمن',               'textarea', { rows: 2 }),
                    field('left_sig',                'وظيفة واسم التوقيع الأيسر',               'textarea', { rows: 2 }),
                ],
                { gradient: 'from-cyan-600 to-teal-700', badge: 'الأكثر استخداماً', sort_order: 1 }
            ),
            form('exam-analysis',
                'تقرير تحليل نتائج اختبار',
                'تقرير تحليل شامل لنتائج اختبار مع إحصائيات وتوزيع الدرجات',
                [
                    field('edu_school',              'إدارة التعليم، اسم المدرسة',              'textarea', { rows: 3 }),
                    field('academic_year',           'العام الدراسي',                           'text'),
                    field('semester',                'الفصل الدراسي',                           'text'),
                    field('subject',                 'المادة',                                  'text', { required: true }),
                    field('grade',                   'الصف',                                    'text', { required: true }),
                    field('teacher',                 'اسم المعلم',                              'text', { required: true }),
                    field('exam_type',               'نوع الاختبار',                            'text'),
                    field('students_count',          'عدد الطلاب',                              'text'),
                    field('pass_count',              'عدد الناجحين',                            'text'),
                    field('fail_count',              'عدد الراسبين',                            'text'),
                    field('highest',                 'أعلى درجة',                               'text'),
                    field('lowest',                  'أدنى درجة',                               'text'),
                    field('average',                 'المتوسط العام',                           'text'),
                    field('distribution',            'توزيع الدرجات',                           'textarea', { rows: 5 }),
                    field('analysis',                'تحليل النتائج',                           'textarea', { rows: 4 }),
                    field('recommendations',         'التوصيات',                                'textarea', { rows: 3 }),
                    field('right_sig',               'وظيفة واسم التوقيع الأيمن',               'textarea', { rows: 2 }),
                    field('left_sig',                'وظيفة واسم التوقيع الأيسر',               'textarea', { rows: 2 }),
                ],
                { gradient: 'from-teal-600 to-emerald-700', sort_order: 2 }
            ),
            form('pre-post-analysis',
                'تحليل نتائج الاختبار القبلي والبعدي',
                'تقرير مقارنة نتائج الاختبار القبلي والبعدي لقياس أثر التدريس',
                [
                    field('edu_school',              'إدارة التعليم، اسم المدرسة',              'textarea', { rows: 3 }),
                    field('academic_year',           'العام الدراسي',                           'text'),
                    field('semester',                'الفصل الدراسي',                           'text'),
                    field('subject',                 'المادة',                                  'text', { required: true }),
                    field('grade',                   'الصف',                                    'text', { required: true }),
                    field('teacher',                 'اسم المعلم',                              'text', { required: true }),
                    field('students_count',          'عدد الطلاب',                              'text'),
                    field('pre_average',             'متوسط الاختبار القبلي',                   'text'),
                    field('post_average',            'متوسط الاختبار البعدي',                   'text'),
                    field('improvement',             'نسبة التحسن',                             'text'),
                    field('pre_results',             'نتائج الاختبار القبلي التفصيلية',         'textarea', { rows: 5 }),
                    field('post_results',            'نتائج الاختبار البعدي التفصيلية',         'textarea', { rows: 5 }),
                    field('analysis',                'تحليل المقارنة',                          'textarea', { rows: 4 }),
                    field('recommendations',         'التوصيات',                                'textarea', { rows: 3 }),
                    field('right_sig',               'وظيفة واسم التوقيع الأيمن',               'textarea', { rows: 2 }),
                    field('left_sig',                'وظيفة واسم التوقيع الأيسر',               'textarea', { rows: 2 }),
                ],
                { gradient: 'from-emerald-600 to-green-700', sort_order: 3 }
            ),
            form('diagnostic-test',
                'تقرير اختبار تشخيصي',
                'نموذج توثيق نتائج الاختبار التشخيصي وتحديد مستويات الطلاب',
                [
                    field('edu_school',              'إدارة التعليم، اسم المدرسة',              'textarea', { rows: 3 }),
                    field('academic_year',           'العام الدراسي',                           'text'),
                    field('semester',                'الفصل الدراسي',                           'text'),
                    field('subject',                 'المادة',                                  'text', { required: true }),
                    field('grade',                   'الصف',                                    'text', { required: true }),
                    field('teacher',                 'اسم المعلم',                              'text', { required: true }),
                    field('test_date',               'تاريخ الاختبار',                          'text'),
                    field('students_count',          'عدد المستهدفين',                          'text'),
                    field('description',             'الوصف',                                   'textarea', { rows: 4 }),
                    field('strengths',               'نقاط القوة',                              'textarea', { rows: 4 }),
                    field('weaknesses',              'نقاط الضعف وأسبابها',                     'textarea', { rows: 4 }),
                    field('recommendations',         'التوصيات',                                'textarea', { rows: 5 }),
                    field('image1',                  'صورة الشاهد الأول',                       'image'),
                    field('image2',                  'صورة الشاهد الثاني',                      'image'),
                    field('right_sig',               'وظيفة واسم التوقيع الأيمن',               'textarea', { rows: 2 }),
                    field('left_sig',                'وظيفة واسم التوقيع الأيسر',               'textarea', { rows: 2 }),
                ],
                { gradient: 'from-green-600 to-teal-700', sort_order: 4 }
            ),
        ],
    },

    // ─── 5. الخطة الأسبوعية ─────────────────────────────────────────────
    {
        title_ar: 'الخطة الأسبوعية',
        title_en: 'Weekly Plan Builder',
        description_ar: 'إنشاء الخطط الأسبوعية المنهجية بتصاميم احترافية',
        icon: 'CalendarDays',
        gradient: 'from-amber-600 to-orange-600',
        href: '/weekly-plan-builder',
        sort_order: 5,
        is_active: true,
        forms: [

            form('weekly-plan',
                'الخطة الأسبوعية',
                'نموذج الخطة الأسبوعية للتدريس',
                [
                    field('school_name',  'اسم المدرسة',      'text',     { required: true }),
                    field('teacher_name', 'اسم المعلم/ة',     'text',     { required: true }),
                    field('subject',      'المادة',           'text',     { required: true }),
                    field('grade',        'الصف',             'text' ),
                    field('week_from',    'من تاريخ',         'text' ),
                    field('week_to',      'إلى تاريخ',        'text' ),
                    field('unit_name',    'اسم الوحدة',       'text' ),
                    field('lesson_1',     'الدرس – الأحد',    'text' ),
                    field('lesson_2',     'الدرس – الاثنين',  'text' ),
                    field('lesson_3',     'الدرس – الثلاثاء', 'text' ),
                    field('lesson_4',     'الدرس – الأربعاء', 'text' ),
                    field('lesson_5',     'الدرس – الخميس',   'text' ),
                    field('objectives',   'الأهداف العامة',   'textarea', { rows: 3 }),
                    field('resources',    'المصادر والوسائل', 'textarea', { rows: 2 }),
                    field('notes',        'ملاحظات',          'textarea', { rows: 2 }),
                ],
                { gradient: 'from-amber-500 to-orange-600' }
            ),
        
        ],
    },

    // ─── 6. شهادات شكر وتقدير ───────────────────────────────────────────
    {
        title_ar: 'شهادات شكر وتقدير',
        title_en: 'Appreciation Certificates',
        description_ar: 'إنشاء شهادات الشكر والتقدير بتصاميم احترافية متعددة',
        icon: 'Award',
        gradient: 'from-yellow-500 to-amber-600',
        href: '/appreciation-certificates',
        sort_order: 6,
        is_active: true,
        forms: [

            form('appreciation-cert',
                'شهادة شكر وتقدير',
                'نموذج إنشاء شهادة شكر وتقدير احترافية',
                [
                    field('recipient_name',  'اسم المُكرَّم/ة',      'text',     { required: true }),
                    field('recipient_title', 'الوظيفة/المنصب',       'text' ),
                    field('issuer_name',     'جهة الإصدار',           'text',     { required: true }),
                    field('reason',          'سبب التكريم',           'textarea', { rows: 3 }),
                    field('date',            'تاريخ الإصدار',         'text' ),
                    field('school_name',     'اسم المدرسة',           'text' ),
                    field('principal_name',  'مدير المدرسة',          'text' ),
                    field('supervisor_name', 'اسم مدير التعليم',      'text' ),
                    field('logo',            'شعار المدرسة',          'image' ),
                ],
                { gradient: 'from-yellow-500 to-amber-600' }
            ),
        
        ],
    },

    // ─── 7. شهادات متنوعة ───────────────────────────────────────────────
    {
        title_ar: 'شهادات متنوعة',
        title_en: 'Various Certificates',
        description_ar: 'شهادات تخرج، مشاركة، إنجاز، وتدريب بتصاميم متعددة',
        icon: 'Award',
        gradient: 'from-orange-500 to-red-600',
        href: '/other-certificates',
        sort_order: 7,
        is_active: true,
        forms: [

            form('participation-cert',
                'شهادة مشاركة',
                'شهادة مشاركة في برامج وفعاليات تعليمية',
                [
                    field('recipient_name',  'اسم المشارك/ة',    'text',     { required: true }),
                    field('event_name',      'اسم البرنامج/الفعالية', 'text', { required: true }),
                    field('date',            'تاريخ الفعالية',   'text' ),
                    field('duration',        'مدة الفعالية',     'text' ),
                    field('issuer',          'جهة الإصدار',      'text' ),
                    field('school_name',     'اسم المدرسة',      'text' ),
                    field('notes',           'ملاحظات',          'textarea', { rows: 2 }),
                ],
                { gradient: 'from-orange-500 to-amber-600' }
            ),
        
        ],
    },

    // ─── 8. المجتمع المهني ──────────────────────────────────────────────
    {
        title_ar: 'المجتمع المهني',
        title_en: 'Professional Community',
        description_ar: 'نماذج المجتمعات المهنية التعلمية وتوثيق اجتماعاتها',
        icon: 'Users',
        gradient: 'from-indigo-600 to-blue-700',
        href: '/professional-community',
        sort_order: 8,
        is_active: true,
        forms: [

            form('professional-community-meeting',
                'محضر اجتماع المجتمع المهني',
                'توثيق اجتماع المجتمع المهني التعلمي',
                [
                    field('community_name',  'اسم المجتمع المهني',  'text',     { required: true }),
                    field('school_name',     'اسم المدرسة',         'text',     { required: true }),
                    field('meeting_date',    'تاريخ الاجتماع',      'text' ),
                    field('meeting_time',    'وقت الاجتماع',        'text' ),
                    field('venue',           'مكان الاجتماع',       'text' ),
                    field('attendees',       'أسماء الحضور',        'textarea', { rows: 4 }),
                    field('agenda',          'جدول الأعمال',        'textarea', { rows: 4 }),
                    field('decisions',       'القرارات والتوصيات',   'textarea', { rows: 4 }),
                    field('next_meeting',    'موعد الاجتماع القادم', 'text' ),
                    field('facilitator',     'المُيَسِّر/ة',        'text' ),
                    field('recorder',        'المُدَوِّن/ة',        'text' ),
                    field('image1',          'صورة توثيقية',        'image' ),
                ],
                { gradient: 'from-indigo-500 to-blue-600' }
            ),
        
        ],
    },

    // ─── 9. المبادرات المدرسية ──────────────────────────────────────────
    {
        title_ar: 'المبادرات المدرسية',
        title_en: 'School Initiatives',
        description_ar: 'توثيق المبادرات المدرسية الإبداعية وتقاريرها',
        icon: 'Sparkles',
        gradient: 'from-pink-600 to-rose-700',
        href: '/school-initiatives',
        sort_order: 9,
        is_active: true,
        forms: [

            form('initiative-report',
                'تقرير مبادرة مدرسية',
                'نموذج توثيق المبادرات المدرسية',
                [
                    field('initiative_name', 'اسم المبادرة',      'text',     { required: true }),
                    field('school_name',     'اسم المدرسة',       'text',     { required: true }),
                    field('initiator',       'صاحب المبادرة',     'text' ),
                    field('start_date',      'تاريخ البدء',       'text' ),
                    field('end_date',        'تاريخ الانتهاء',    'text' ),
                    field('objectives',      'أهداف المبادرة',    'textarea', { rows: 4 }),
                    field('description',     'وصف المبادرة',      'textarea', { rows: 4 }),
                    field('beneficiaries',   'المستفيدون',        'text' ),
                    field('results',         'النتائج والمؤشرات', 'textarea', { rows: 3 }),
                    field('image1',          'صورة المبادرة',     'image' ),
                    field('image2',          'صورة إضافية',       'image' ),
                    field('evidence_url',    'رابط الشواهد',      'url' ),
                ],
                { gradient: 'from-pink-500 to-rose-600' }
            ),
        
        ],
    },

    // ─── 10. تحسين النتائج ───────────────────────────────────────────────
    {
        title_ar: 'تحسين النتائج',
        title_en: 'Improve Results',
        description_ar: 'خطط وبرامج تحسين نتائج الطلاب والارتقاء بمستوياتهم',
        icon: 'TrendingUp',
        gradient: 'from-green-600 to-emerald-700',
        href: '/improve-results',
        sort_order: 10,
        is_active: true,
        forms: [
            form('honor-students',
                'تقرير تكريم الطلاب والطالبات المتفوقين',
                'نموذج توثيق تكريم الطلاب والطالبات المتفوقين وتحفيزهم على الاستمرار في التميز',
                [
                    field('edu_school',              'إدارة التعليم، اسم المدرسة',              'textarea', { rows: 4 }),
                    field('academic_year',           'العام الدراسي',                           'text'),
                    field('semester',                'الفصل الدراسي',                           'text'),
                    field('event_date',              'تاريخ التنفيذ',                           'text'),
                    field('duration',                'مدة التنفيذ',                             'text'),
                    field('location',                'مكان التنفيذ',                            'text'),
                    field('grade',                   'الصف',                                    'text'),
                    field('target_group',            'الفئة المستهدفة',                         'text'),
                    field('count',                   'العدد',                                   'text'),
                    field('description',             'الوصف',                                   'textarea', { rows: 5 }),
                    field('objectives',              'الأهداف',                                 'textarea', { rows: 6 }),
                    field('implementation',          'آلية التنفيذ',                            'textarea', { rows: 6 }),
                    field('recommendations',         'التوصيات',                                'textarea', { rows: 5 }),
                    field('image1',                  'صورة الشاهد الأول',                       'image'),
                    field('image2',                  'صورة الشاهد الثاني',                      'image'),
                    field('right_sig',               'وظيفة واسم التوقيع الأيمن',               'textarea', { rows: 2 }),
                    field('left_sig',                'وظيفة واسم التوقيع الأيسر',               'textarea', { rows: 2 }),
                ],
                { gradient: 'from-emerald-600 to-green-700', badge: 'الأكثر استخداماً', sort_order: 1 }
            ),
        ],
    },

    // ─── 12. التقاويم الأكاديمية ─────────────────────────────────────────
    {
        title_ar: 'التقاويم الأكاديمية',
        title_en: 'Academic Calendars',
        description_ar: 'إنشاء التقاويم الأكاديمية الدراسية بتصاميم احترافية',
        icon: 'CalendarDays',
        gradient: 'from-teal-600 to-cyan-700',
        href: '/academic-calendars',
        sort_order: 12,
        is_active: true,
        forms: [

            form('academic-calendar',
                'التقويم الأكاديمي',
                'نموذج إنشاء التقويم الأكاديمي',
                [
                    field('school_name',     'اسم المدرسة',        'text',     { required: true }),
                    field('academic_year',   'العام الدراسي',       'text',     { required: true }),
                    field('first_semester_start', 'بداية الفصل الأول',  'text' ),
                    field('first_semester_end',   'نهاية الفصل الأول',  'text' ),
                    field('second_semester_start','بداية الفصل الثاني', 'text' ),
                    field('second_semester_end',  'نهاية الفصل الثاني', 'text' ),
                    field('holidays',        'الإجازات والعطل',     'textarea', { rows: 5 }),
                    field('events',          'الأحداث المدرسية',    'textarea', { rows: 5 }),
                    field('exams_schedule',  'جدول الاختبارات',     'textarea', { rows: 4 }),
                    field('principal_name',  'مدير المدرسة',        'text' ),
                ],
                { gradient: 'from-teal-500 to-cyan-600' }
            ),
        
        ],
    },

    // ─── 13. البيئة المدرسية ─────────────────────────────────────────────
    {
        title_ar: 'البيئة المدرسية',
        title_en: 'School Environment',
        description_ar: 'نماذج تقييم وتوثيق البيئة المدرسية الجاذبة',
        icon: 'BookOpen',
        gradient: 'from-lime-600 to-green-700',
        href: '/school-environment',
        sort_order: 13,
        is_active: true,
        forms: [
            form('student-activity',
                'بطاقة تنفيذ برنامج النشاط الطلابي',
                'بطاقة توثيق تنفيذ برنامج النشاط الطلابي مع قوائم المشاركين والشواهد',
                [
                    field('edu_school',              'إدارة التعليم، اسم المدرسة',              'textarea', { rows: 4 }),
                    field('academic_year',           'العام الدراسي',                           'text'),
                    field('semester',                'الفصل الدراسي',                           'text'),
                    field('activity_name',           'اسم البرنامج / النشاط',                   'text', { required: true }),
                    field('day',                     'اليوم والتاريخ',                          'text'),
                    field('time',                    'الوقت والفترة',                           'text'),
                    field('supervisor',              'اسم المشرف على البرنامج',                 'text', { required: true }),
                    field('grade',                   'الصف',                                    'text'),
                    field('target_group',            'الفئة المستهدفة',                         'text'),
                    field('students_count',          'عدد المستهدفين',                          'text'),
                    field('participants_count',      'عدد المشاركين من أسماء البرنامج',         'text'),
                    field('absent_count',            'المتأخرون من أسماء البرنامج',             'text'),
                    field('activity_type',           'نوع تقييم البرنامج',                      'text'),
                    field('objectives',              'الأهداف',                                 'textarea', { rows: 4 }),
                    field('image1',                  'صورة الشاهد الأول',                       'image'),
                    field('image2',                  'صورة الشاهد الثاني',                      'image'),
                    field('right_sig',               'وظيفة واسم التوقيع الأيمن',               'textarea', { rows: 2 }),
                    field('left_sig',                'وظيفة واسم التوقيع الأيسر',               'textarea', { rows: 2 }),
                ],
                { gradient: 'from-green-600 to-emerald-700', badge: 'الأكثر استخداماً', sort_order: 1 }
            ),
        ],
    },

    // ─── 14. تفاعل أولياء الأمور ─────────────────────────────────────────
    {
        title_ar: 'تفاعل أولياء الأمور',
        title_en: 'Parents Interaction',
        description_ar: 'نماذج وأدوار التواصل والتفاعل مع أولياء الأمور',
        icon: 'Users',
        gradient: 'from-sky-600 to-blue-700',
        href: '/parents-interaction',
        sort_order: 14,
        is_active: true,
        forms: [

            form('parent-meeting',
                'محضر اجتماع أولياء الأمور',
                'توثيق اجتماعات أولياء الأمور وقراراتها',
                [
                    field('school_name',    'اسم المدرسة',          'text',     { required: true }),
                    field('meeting_date',   'تاريخ الاجتماع',       'text' ),
                    field('meeting_time',   'وقت الاجتماع',         'text' ),
                    field('venue',          'مكان الاجتماع',        'text' ),
                    field('attendees_count','عدد الحضور',           'number' ),
                    field('agenda',         'جدول الأعمال',         'textarea', { rows: 4 }),
                    field('discussion',     'ما دار في الاجتماع',   'textarea', { rows: 5 }),
                    field('decisions',      'القرارات والتوصيات',    'textarea', { rows: 4 }),
                    field('facilitator',    'رئيس الاجتماع',        'text' ),
                    field('recorder',       'المُدَوِّن/ة',         'text' ),
                    field('image1',         'صورة الاجتماع',        'image' ),
                ],
                { gradient: 'from-sky-500 to-blue-600' }
            ),
        
        ],
    },

    // ─── 15. لوحات وبنرات ────────────────────────────────────────────────
    {
        title_ar: 'لوحات وبنرات',
        title_en: 'Signs & Banners',
        description_ar: 'تصميم لوحات وبنرات مدرسية بأحجام ومحتويات مخصصة',
        icon: 'Layers',
        gradient: 'from-slate-600 to-gray-700',
        href: '/signs-banners',
        sort_order: 15,
        is_active: true,
        forms: [

            form('banner-design',
                'تصميم لوحة أو بنر',
                'نموذج تصميم لوحة أو بنر مدرسي',
                [
                    field('title',       'عنوان اللوحة',          'text',     { required: true }),
                    field('subtitle',    'العنوان الفرعي',         'text' ),
                    field('school_name', 'اسم المدرسة',            'text' ),
                    field('body_text',   'النص الرئيسي',           'textarea', { rows: 5 }),
                    field('size',        'حجم اللوحة',             'select',   { options: ['A4 عمودي','A4 أفقي','A3 عمودي','A3 أفقي','50×70cm','100×80cm'] }),
                    field('image1',      'صورة رئيسية',            'image' ),
                    field('logo',        'شعار المدرسة',           'image' ),
                    field('date',        'التاريخ',                'text' ),
                    field('notes',       'ملاحظات التصميم',        'textarea', { rows: 2 }),
                ],
                { gradient: 'from-slate-500 to-gray-600' }
            ),
        
        ],
    },

    // ─── 16. استبيانات أنماط التعلم ──────────────────────────────────────
    {
        title_ar: 'استبيانات أنماط التعلم',
        title_en: 'Learning Style Surveys',
        description_ar: 'استبيانات تحديد أنماط التعلم وتوزيع الطلاب وفق أسلوب تعلمهم',
        icon: 'Brain',
        gradient: 'from-purple-600 to-violet-700',
        href: '/learning-style-surveys',
        sort_order: 16,
        is_active: true,
        forms: [

            form('program-activity-advanced',
                'نموذج توثيق برنامج أو نشاط (المطور)',
                'نموذج توثيق يقبل رفع شاهد واحد كحد أدنى وشاهدين كحد أقصى مع إمكانية وضع رابط يتحول لباركود',
                [
                    field('education_dept',    'إدارة التعليم',             'text',     { placeholder_ar: 'الإدارة العامة للتعليم بالمنطقة', required: true }),
                    field('school_name',       'اسم المدرسة',               'text',     { placeholder_ar: 'مدرسة', required: true }),
                    field('program_name',      'اسم البرنامج / المبادرة',   'text',     { placeholder_ar: 'تقرير الاحتفاء باليوم الوطني ٩٥', required: true }),
                    field('implementors',      'المنفذ/ون',                 'text',     { placeholder_ar: 'جميع منسوبي المدرسة' }),
                    field('participants',      'المشاركـ/ون',               'text',     { placeholder_ar: 'أولياء الأمور' }),
                    field('location',          'مكان التنفيذ',              'text',     { placeholder_ar: 'فناء المدرسة' }),
                    field('duration',          'مدة التنفيذ',               'text',     { placeholder_ar: 'يوم واحد' }),
                    field('date',              'تاريخ التنفيذ',             'text',     { placeholder_ar: '١/٤/١٤٤٧هـ' }),
                    field('beneficiaries',     'المستفيدون / عددهم',        'text',     { placeholder_ar: 'منسوبي المدرسة / أولياء الأمور' }),
                    field('domain',            'المجال',                    'text',     { placeholder_ar: 'المواطنة' }),
                    field('objectives',        'الأهداف',                   'textarea', { rows: 5, placeholder_ar: 'تعزيز الهوية الوطنية والانتماء...' }),
                    field('steps',             'خطوات التنفيذ / الوصف',     'textarea', { rows: 5 }),
                    field('right_signature_title', 'وظيفة التوقيع الأيمن', 'text',     { placeholder_ar: 'رائد النشاط' }),
                    field('right_signature_name',  'الاسم (توقيع أيمن)',    'text',     { placeholder_ar: 'الاسم' }),
                    field('left_signature_title',  'وظيفة التوقيع الأيسر', 'text',     { placeholder_ar: 'مدير المدرسة' }),
                    field('left_signature_name',   'الاسم (توقيع أيسر)',    'text',     { placeholder_ar: 'الاسم' }),
                    field('image1',            'صورة الشاهد الأول',         'image',    { required: true }),
                    field('image2',            'صورة الشاهد الثاني (اختياري)', 'image' ),
                    field('evidence_url',      'رابط الشواهد (باركود تلقائي)', 'url',  { placeholder_ar: 'سيتم إنشاء باركود تلقائياً' }),
                ],
                { badge: 'الأكثر استخداماً', gradient: 'from-blue-500 to-blue-600' }
            ),
            form('strategy-brief',
                'نموذج تنفيذ استراتيجية مختصرة',
                'نموذج مختصر لتوثيق تنفيذ استراتيجية تعليمية',
                [
                    field('education_dept', 'إدارة التعليم/المنطقة/مكتب التعليم', 'textarea', { rows: 3 }),
                    field('school_name',    'اسم المدرسة',                'text',     { required: true }),
                    field('date',           'تاريخ التنفيذ',              'text' ),
                    field('subject',        'المادة',                     'text' ),
                    field('strategy',       'استراتيجية التعلم',          'text',     { required: true }),
                    field('students_count', 'عدد المستفيدين',             'text' ),
                    field('grade',          'المرحلة الدراسية',           'text' ),
                    field('class',          'الفصل',                      'text' ),
                    field('lesson',         'اسم الدرس',                  'text' ),
                    field('objectives',     'الأهداف',                    'textarea', { rows: 5 }),
                    field('teacher_name',   'اسم المعلم',                 'textarea', { rows: 2 }),
                    field('other_name',     'اسم آخر',                    'textarea', { rows: 2 }),
                    field('twitter',        'حساب تويتر',                 'text',     { placeholder_ar: '@' }),
                    field('image1',         'الشاهد الأول',               'image' ),
                    field('image2',         'الشاهد الثاني',              'image' ),
                ],
                { gradient: 'from-emerald-500 to-green-600' }
            ),
            form('program-coverage',
                'تقرير تنفيذ برنامج (تغطية)',
                'تقرير تغطية لتنفيذ برنامج مع شاهد واحد',
                [
                    field('education_dept', 'إدارة التعليم', 'textarea', { rows: 3 }),
                    field('edu_office',     'مكتب التعليم',  'text' ),
                    field('program_name',   'اسم البرنامج',  'text', { required: true }),
                    field('date',           'تاريخ التنفيذ', 'text' ),
                    field('targets',        'المستهدفون',    'text' ),
                    field('domain',         'المجال',        'text' ),
                    field('objectives',     'الأهداف',       'textarea', { rows: 5 }),
                    field('steps',          'خطوات التنفيذ', 'textarea', { rows: 5 }),
                    field('image1',         'الشاهد الأول',  'image' ),
                    field('image2',         'الشاهد الثاني', 'image' ),
                    field('image3',         'الشاهد الثالث', 'image' ),
                    field('teacher_name',   'اسم المعلم/ة',  'textarea', { rows: 4 }),
                ],
                { gradient: 'from-violet-500 to-purple-600' }
            ),
        
        ],
    },

];
